### ISSUE TITLE
screenFetch displays the wrong font on Yosemite

### ISSUE THREAD

**Issue by hghtmes** [KittyKatt/screenFetch#150]
Hi, just tried screenFetch and it displays my font as Monaco 9 regardless of what I actually have the font set as

**Comment by JadeMatrix** [comment]
I might have inadvertently fixed this with PR #327, but I'm on 10.9 so I can't completely confirm.

**Comment by darealshinji** [comment]
Changes from PR #327 have been added manually. Just close this issue if it has been fixed for you @hghtmes .
