### ISSUE TITLE
Emoticons and icons displayed on Icons section in KDE

### ISSUE THREAD

**Issue by mulus-armatus** [KittyKatt/screenFetch#162]
In the icons info, it shows the emoticon theme ("Never mind!"), and then the icon theme ("Flamini") in a new line.
My output:

 martin@delorean
 OS: Fedora 20 Heisenbug
 Kernel: x86_64 Linux 3.16.6-200.fc20.x86_64
 Uptime: 3h 53m
 Packages: 2000
 Shell: bash 4.2.53
 Resolution: 1366x768
 DE: KDE 4.14.2
 WM: KWin
 WM Theme: Aurorae
 Gtk Theme: qtcurve [GTK2], Not Found [GTK3]
 Icon Theme: Never mind!
Flamini
 Font: Not Found
 CPU: Intel Core i5-3337U CPU @ 2.7GHz
 GPU: GeForce GT 730M
 RAM: 2412MB / 7850MB

**Comment by KittyKatt** [comment]
KDE4 no longer supported.
