### ISSUE TITLE
Display cursor theme

### ISSUE THREAD

**Issue by darealshinji** [KittyKatt/screenFetch#175]
Can you let screenfetch display the cursor theme?

**Comment by darealshinji** [comment]
Okay, in gnome-based DEs the value can be obtained with gsettings.

MATE: `gsettings get org.mate.peripherals-mouse cursor-theme`
Gnome (and Unity?): `gsettings get org.gnome.desktop.interface cursor-theme`

**Comment by KittyKatt** [comment]
Hmmmm. Possibly. But I would assume that there's really not a standard for saving cursor themes. Might be a bit to write to cover all cases. I'll consider it, at least.
