### ISSUE TITLE
Mis-detected Debian Sid as Jessie

### ISSUE THREAD

**Issue by wyatt8740** [KittyKatt/screenFetch#180]
I initially installed jessie but then changed all my sources.list to use sid. But screenfetch lists my computer as Debian 8.0 Jessie. Either it's looking in the wrong place, or I'm doing something wrong.

I noticed /etc/os-release calls mine Jessie; what should it say for Sid? And anyway, I think detection based on sources.list would be a better solution.

``` #

# deb cdrom:[Debian GNU/Linux testing _Jessie_ - Official Snapshot amd64 DVD Binary-1 20140512-06:22]/ jessie contrib main

#deb cdrom:[Debian GNU/Linux testing _Jessie_ - Official Snapshot amd64 DVD Binary-1 20140512-06:22]/ jessie contrib main

#SID SOURCES

deb http://ftp.us.debian.org/debian/ sid main contrib
deb-src http://ftp.us.debian.org/debian/ sid main contrib

# nonfree
deb http://http.debian.net/debian/ sid main contrib non-free

```

Below that are all my (commented out) jessie sources.

**Comment by GLolol** [comment]
This is stored in `/etc/debian_version` (package `base-files`). Often times sid will use the same numeric as testing until the next release comes out.

**Comment by wyatt8740** [comment]
Wouldn't it be better to read sources.list and (for the main debian mirrors anyway) check the release name there?

**Comment by GLolol** [comment]
You can mix different repositories together in sources.list; which one would you look for in such a case? (Ubuntu PPAs, etc. can be added on Debian)

**Comment by wyatt8740** [comment]
In the case of mixed sources, I would fall back to the older /etc/os-release method (besides with differences between sid and unstable, which are identical).

**Comment by darealshinji** [comment]
According to my understanding those files like `/etc/os-release` are there to make it possible or easier to identify your distro and release version. If you do an upgrade by changing **all** the sources to Sid, it would make sense edit those files too.
