### ISSUE TITLE
Displaying extras new lines when Distro Logo is disabled

### ISSUE THREAD

**Issue by andresperezl** [KittyKatt/screenFetch#184]
When the Distrubiton logo is disabled there is too much space between the lines in the output 
````
andres@vmserver:~$ ./screenfetch-dev -nEN
 andres@vmserver
 OS: Ubuntu 14.04 trusty
 Kernel: x86_64 Linux 3.16.0-30-generic
 Uptime: 5h 1m
 Packages: 559
 Shell: bash 4.3.11







 CPU: AMD FX-8150 Eight-Core @ 3.64GHz

 RAM: 77MB / 2001MB
````

To get rid of the blank lines I piped `screenfetch` with `sed`
````
./scripts/screenfetch-dev -nNE | sed '/^\s*$/d'
````

**Comment by darealshinji** [comment]
The same happens for me too if I switch to tty1 and run `./screenfetch-dev -nEN` but it looks normal if I run it within a window manager.

**Comment by andresperezl** [comment]
Yes  indeed, I forgot to say that I was running the script through SSH in an virtual machine Ubuntu Server

**Comment by KittyKatt** [comment]
Yeah, -n isn't very smart right now. It just removes the lines that that don't exist, so blank lines. It's on my TODO list to fix.
