### ISSUE TITLE
empty stderrOut file created on each run

### ISSUE THREAD

**Issue by darealshinji** [KittyKatt/screenFetch#194]
Since commit https://github.com/KittyKatt/screenFetch/commit/d9fe5659916877ef9356c6692f9b3c3bcca46b7d an empty text file with the name stderrOut is created whenever I run screenfetch. This is kinda annoying.

**Comment by Explouad** [comment]
Can't you just take that line out?

**Comment by darealshinji** [comment]
It seems like this part between line 3707 and 3711 is essential for the script to work.
However it could be either piped to `/dev/null` or to a file in `/tmp` or `/var/tmp`.

**Comment by darealshinji** [comment]
And there it happened: https://github.com/KittyKatt/screenFetch/commit/69567b963a3d1bf672351df6ee7d3eb785d9eb72#diff-33bbb23e0cfd07bcac62273e189d2374

**Comment by GLolol** [comment]
I don't understand. d9fe565 was talking about fixing a syntax error, but that was never a problem for me. bash 4.2 and 4.3 (as far as I can tell) don't have that problem at all; perhaps @ryanpcmcquen is using a version that's too old?

**Comment by ryanpcmcquen** [comment]
I am using 4.3.30.

**Comment by GLolol** [comment]
Bash 4.3.33 on Arch Linux. Just tried it now with d9fe565 reverted, and I can't reproduce a syntax error.

**Comment by ryanpcmcquen** [comment]
Maybe tmux is a factor? My environment is pretty clean.

**Comment by ryanpcmcquen** [comment]
OK, just tested here on a fresh machine and everything works with that original line. Sorry for creating this issue, I don't know what was going on in my old environment that it wasn't interpreting that.  :-(

@KittyKatt please revert https://github.com/KittyKatt/screenFetch/pull/192
