### ISSUE TITLE
screenfetch doesn't detect several things in Ubuntu Unity (14.04)

### ISSUE THREAD

**Issue by mikotohe2** [KittyKatt/screenFetch#224]
In Unity (using unity-tweak-tool to set GTK theme, etc), several things are listed as "Not Found"
- GTK Theme (Both 2 and 3)
- Icon Theme
- System Font  
![screenshot from 2015-04-06 13 51 49](https://cloud.githubusercontent.com/assets/5414038/7004501/18013b8e-dc64-11e4-822f-4d1dbc74dff5.png)

**Comment by darealshinji** [comment]
If you say it doesn't detect this in Unity, does it work for you if you run it in another desktop environment?
And the script doesn't seem to be the latest version, because the yellow Ubuntu logo was already removed. Can you check if you get the same issue on the current version?

**Comment by mikotohe2** [comment]
I can't be sure of another desktop environment; I don't have another installed to test with. However after updating to the latest screenfetch, the issue still persists.

**Comment by rtlanceroad** [comment]
While I minimal installed ubuntu 14.04 from mini.iso, and with fluxbox. Everything is just fine.  I've found screenfetch is not in ubuntu official repository, so you may git this repo && rename screenfetch-dev to screenfetch && make screenfetch executable && copy screenfetch to /usr/bin.

**Comment by KittyKatt** [comment]
From IRC:

Can you give me the output of the following?
`gsettings get org.gnome.desktop.interface gtk-theme`
`gsettings get org.gnome.desktop.interface icon-theme`
`gsettings get org.gnome.desktop.interface font-name`

And separately,
`gconftool-2 -g /desktop/gnome/interface/gtk_theme`
`gconftool-2 -g /desktop/gnome/interface/icon_theme`
`gconftool-2 -g /desktop/gnome/interface/font_name`

**Comment by KittyKatt** [comment]
So, definitely not even detecting Unity running. That's the real problem. Gonna look into that.

**Comment by mikotohe2** [comment]
Confirmed working with most recent commit.
