### ISSUE TITLE
Let's implement it for Lunar Linux support

### ISSUE THREAD

**Issue by rtlanceroad** [KittyKatt/screenFetch#228]
The logo is below:
![design_lunarlinux_logo](https://cloud.githubusercontent.com/assets/7656607/7036768/e7a32142-ddca-11e4-9312-ed8b325adfc0.jpg)

Below is the related info:

lee@lunar ~ $ cat /etc/os-release 
NAME="Lunar Linux"
VERSION="1.7.0-x86_64 (Sinus Successus)"
ID=lunar
VERSION_ID=1.7.0-x86_64
PRETTY_NAME="Lunar Linux 1.7.0-x86_64 (Sinus Successus - 20141011)"
ANSI_COLOR="1;34"
HOME_URL="http://lunar-linux.org/"

lee@lunar ~ $ cat /etc/lsb-release 
DISTRIB_ID="Lunar Linux"
DISTRIB_RELEASE="1.7.0-x86_64"
DISTRIB_CODENAME="Sinus Successus"
DISTRIB_DESCRIPTION="Lunar Linux 1.7.0-x86_64 (Sinus Successus - 20141011)"

lee@lunar ~ $ cat /etc/issue
Lunar Linux 1.7.0-x86_64 (Sinus Successus - 20141011)
Kernel \r on an \m

**Comment by KittyKatt** [comment]
Oh, this'll be fun! I'll add this to my TODO list for sure. I'll ASCII that logo sometime tonight or tomorrow.

**Comment by KittyKatt** [comment]
Is there a way to detect package counts in Lunar?

**Comment by rtlanceroad** [comment]
Yeah, it should be like this: 

lee@lunar ~ $ lvu installed | wc -l
449

**Comment by KittyKatt** [comment]
@rtlanceroad Please check latest to see if everything is detected and working correctly. :)

**Comment by rtlanceroad** [comment]
@KittyKatt All works perfect except some of them.

screenshot is here:

![2015-05-12-095104_1366x768_scrot](https://cloud.githubusercontent.com/assets/7656607/7578796/fffdc21a-f88c-11e4-96ea-bc5f40ab5f21.png)

i.  In Lunar, echo is stored in /usr/bin, not /bin/echo
    lee@lunar ~ $ whereis echo
    echo: /usr/bin/echo /usr/share/man/man1/echo.1.gz /usr/share/man/man3/echo.3x.gz
ii. CPU detection failed.
iii. Lunar Logo is missing, I believe it's on the half way ^^

**Comment by KittyKatt** [comment]
Ah, that's interesting. Hm. I'll have to think about how to handle that correctly.

**Comment by darealshinji** [comment]
Creating an ASCII logo of that penguin head is quite difficult.
Here's what I got so far:
![lunarscreen](https://cloud.githubusercontent.com/assets/5700937/7927709/500013aa-08e4-11e5-84bf-137df3343765.png)
```
if [[ "$no_color" != "1" ]]; then
	c1=$(getColor 'dark grey') # Dark Gray
	c2=$(getColor 'yellow') # Bold Yellow
	c3=$(getColor 'white') # White
fi
if [ -n "${my_lcolor}" ]; then c1="${my_lcolor}"; c2="${my_lcolor}"; c3="${my_lcolor}"; fi
startline="0"
fulloutput=(
"$c1                   .....................                  %s"
"$c1  ....,       .;d0WMMMMMMMMMMMMMMMMMMMMMKd;.   ...,;;'   %s"
"$c1    .:oOXMWNXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMM0l'     %s"
"$c1       .,:kNMMMMM${c3}i${c1}MMMMMMMMMMMMMMMMMMMMMMM${c3}r${c1}MMMMMWklc;,..  %s"
"$c1  ..,cllod0MMMMMMM${c3}llbo${c1}MMMMMMMMMMMMMMM${c3}cdlf${c1}MMMMMMMXOxdlc:,.%s"
"$c1   ...,ckNMMNXMMMMMM${c3}lkbxo${c1}MMMMMMMMM${c3}cxdkf${c1}MMMMMMMMMMNOdc,.  %s"
"$c1    ,clkNMMMXMMMMMMMMMMMMMMM${c2}+++${c1}MMMMMMMMMMMMMMW,   \`+++...%s"
"$c1  ,cokxl:'\`  ,MMMMMMMMMMMMM${c2}+++++${c1}MMMMMMMMMMMMM,           %s"
"$c1 ''          ,MMMMMMMMMMMMMM${c2}+++${c1}MMMMMMMMMMMMMM,           %s"
"$c1             ,MMMMM${c3}qydkRP${c1}MMMM${c2}+${c1}MMMM${c3}YSRxsp${c1}MMMMM,           %s"
"$c1             ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,           %s"
"$c1              KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO            %s"
"$c1               OMMMMMMMMMMMMMMMMMMMMMMMMMMMk             %s"
"$c1                'xWMMMMMMMMMMMMMMMMMMMMMWx'              %s"
"$c1                   :OWMMMMMMMMMMMMMMMWk:                 %s"
"$c1                      ':oxO0XNX0Okdc'                    %s")
```

**Comment by KittyKatt** [comment]
Ohhhhh, that's not bad at all! I'll yank that from you and maybe improve a bit. Sorry progress has been so slow, got a few other projects on my hands at the moment.

**Comment by rtlanceroad** [comment]
Thanks, you guys.

**Comment by darealshinji** [comment]
Closing this since Lunar is now supported.
