### ISSUE TITLE
Ubuntu Mate - Not Found

### ISSUE THREAD

**Issue by t3kg33k** [KittyKatt/screenFetch#238]
Using Ubuntu Mate 15.04 a lot of information is not displayed. One of the main items is Desktop Environment. Other items missing, displaying 'Not Found':
GTK Theme: Not Found [GTK2], Not Found [GTK3]
Icon Theme: Not Found
Font: Not Found

**Comment by KittyKatt** [comment]
Huh, that's interesting. Wonder what changed.
