### ISSUE TITLE
kali 1.1.0a not correct display

### ISSUE THREAD

**Issue by fhoshino** [KittyKatt/screenFetch#239]
Before 1.1.0, i.e. 1.0.9, screenfetch get the correct distro, but starting from 1.1.0, the distro is unidentifiable. 

➜  ~  screenFetch/screenfetch-dev
                             root@kali
                             OS: Unknown 1.1.0 moto
                             Kernel: x86_64 Linux 3.18.0-kali3-amd64
         #####               Uptime: 14d 22h 31m
        #######              Packages: Unknown
        ##O#O##              Shell: zsh 4.3.17
        #######              CPU: Intel Core i7-3770 CPU @ 3.392GHz
      ###########            RAM: 1020MB / 7990MB
     #############
    ###############
    ################
   #################
 #####################
 #####################
   #################

**Comment by darealshinji** [comment]
What's the output of `lsb_release -idrc`?
What's the content of the following files (if available):
/etc/os-release
/etc/lsb-release
/etc/debian_version

**Comment by fhoshino** [comment]
➜  ~  lsb_release -idrc
Distributor ID: Kali
Description:    Kali GNU/Linux 1.1.0
Release:        1.1.0
Codename:       moto
➜  ~  cat /etc/os-release
cat /etc/debian_versionPRETTY_NAME="Kali GNU/Linux 1.1.0 (moto)"
NAME="Kali GNU/Linux"
ID=kali
VERSION="1.1.0 (moto)"
VERSION_ID="1.1.0"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"
➜  ~  cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=1.1.0
DISTRIB_CODENAME=moto
DISTRIB_DESCRIPTION="Kali GNU/Linux 1.1.0"
➜  ~  cat /etc/debian_version
Kali Linux 1.1.0

**Comment by darealshinji** [comment]
Does changing [this line](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L437) from `"Debian Kali Linux")` to `"Kali"|"Debian Kali Linux")` fix it?

**Comment by fhoshino** [comment]
Yes is does.

**Comment by darealshinji** [comment]
I made a pull request: https://github.com/KittyKatt/screenFetch/pull/240
