### ISSUE TITLE
Adding support for Red Star OS?

### ISSUE THREAD

**Issue by PopeLevi** [KittyKatt/screenFetch#242]
I was wondering if perhaps support for Red Star OS could be added? Here is the logo:

![](http://www.golem.de/1501/sp_111443-92671-i_rc.jpg)

**Comment by KittyKatt** [comment]
Could you give me a little more information on the host system? Perhaps the contents of `/etc/lsb-release` perhaps? Or if there are any unique files that exist in `/etc/` that might make it easier to detect?

**Comment by PopeLevi** [comment]
Sorry, I don't have access to the distro currently, just thought it might be a cool idea

**Comment by darealshinji** [comment]
It's a North Korean Linux distribution: http://en.wikipedia.org/wiki/Red_Star_OS
Someone in the comments section of the Wiki article said it's using RPM.

**Comment by robin0van0der0v** [comment]
@KittyKatt The folder "/etc/lsb-release" doesn't exist. There is a folder called "lsb-release.d" with 4 empty files.
An unique file would be "/etc/redstar-release" which contains "《붉은별》사용자용체계 3.0판" in my installation.
And it does use RPM as @darealshinji points out.
I am currently running Red Star OS in a virtual machine, if you need more information just ask me.

**Comment by KittyKatt** [comment]
Will do. Been SUPER busy with personal stuff lately. I'll come back to this ASAP.

**Comment by darealshinji** [comment]
Detection added in https://github.com/KittyKatt/screenFetch/commit/ea4765864e99b8c5a95ff90e480c9379a1955e15 , tested on release 3.0.
The default bash version is 3, so you need to build version 4 from source. Still need to add a logo. KDE version doesn't show up, need to investigate it.

![redstar](https://cloud.githubusercontent.com/assets/5700937/15377864/268c1da8-1d5f-11e6-8a8b-f726ac40db33.png)

By the way...
Disable malicious components: https://github.com/takeshixx/redstar-tools
Set language to English and other notes: https://richardg867.wordpress.com/2015/01/01/notes-on-red-star-os-3-0/
ISOs: http://www.openingupnorthkorea.com/downloads-2

**Comment by darealshinji** [comment]
Logo added: https://github.com/KittyKatt/screenFetch/commit/2b7e4bb8bca6df20cc060458e12e79f7179bfc4c

**Comment by squirrelandhedgehog** [comment]
Being based on Red Star OS 2.0, it is probably KDE 3.0.
But, I have had trouble configuring panels in KDE3, so it has a chance
of being KDE4. (Plasma 5 did not exist yet.) BTW, I will probably never know as
Red Star OS 3 is not compatible with my computer, unlike Red Star 2.
I know Red Star OS 2 uses KDE3 because I've tested it and Kubuntu 8.04.
Tell me what you think.

**Comment by squirrelandhedgehog** [comment]
Follow up: I wonder why Red Star 2 (2009) is supposed to copy Windows,
but its successor, Red Star 3 (2013) is like Mac OS X.
Maybe it's because 2 was made by Kim Jong-Il, however 3 was made by Kim Jong-Un.

**Comment by MiShiOfficial** [comment]
Anyone been able to run it on bare metal, doesn't seam to run on newer hardware.

**Comment by MiShi-Official** [comment]
Anyway to get it working on modern hardware?
