### ISSUE TITLE
Switch from #! To Vanilla Debian Jessie Distro Name and Logo Issue

### ISSUE THREAD

**Issue by Bukimari** [KittyKatt/screenFetch#247]
Upon the discontinuation of CrunchBang I switched over to vanilla Debian Wheezy, then upgraded to Jessie. Everything seems to have gone smoothly however I've noticed that screenFetch still shows CrunchBang Waldorf as my OS and the #! logo. Gnome settings shows Jessie as the OS (picture below). If it helps, I installed screenFetch back when I was first starting #! and just used the 'git' command as per your installation instructions. I've deleted the screenFetch script and reinstalled using 'apt-get install screenfetch' after the switch however the problem persists. I'm not really very Linux savvy, I rely on tutorials for most things and learn from there, so if this is a simple fix I apologize.
![screenshot - 06072015 - 11 37 53 pm](https://cloud.githubusercontent.com/assets/12791486/8028225/484cc99e-0d6e-11e5-945b-4812078a969d.png)

**Comment by GLolol** [comment]
Your probably have CrunchBang files left over on your system, in which case it's not really a screenFetch problem.

Try removing the files `/etc/crunchbang-lsb-release` and `/etc/lsb-release-crunchbang` if they exist.

**Comment by Bukimari** [comment]
Well that was easy, thanks for the super quick response. Sorry for the unnecessary post, I figured it was something stupidly simple that I just am too new to know about haha.

**Comment by KittyKatt** [comment]
AND CLOSED!
