### ISSUE TITLE
Add support for coreos

### ISSUE THREAD

**Issue by cdancy** [KittyKatt/screenFetch#249]
would be nice...

**Comment by darealshinji** [comment]
I think a little more information would be useful. ;-)
The OS logo. What's the output of `cat /etc/lsb-release` and `cat /etc/os-release`?

**Comment by cdancy** [comment]
Logo=https://www.packet.net/media/labs/images/e4da3b7fbbce2345d7772b0674a318d5/jmrT-coreos-logo.png

lsb-release:

DISTRIB_ID=CoreOS
DISTRIB_RELEASE=681.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 681.0.0"

os-release:

NAME=CoreOS
ID=coreos
VERSION=681.0.0
VERSION_ID=681.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 681.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by cdancy** [comment]
And thanks AOT ;)

**Comment by darealshinji** [comment]
According to Wikipedia CoreOS doesn't use a packet manager. Is that true?

**Comment by cdancy** [comment]
hahahaha yea pretty much ;) The idea is that you get a bare-bones, cloud-centric, OS with which your supposed to run only containers (e.g. docker, rkt, etc..) for your apps and configure only once through a cloud-config file at boot. There's all sorts of bells and whistles (e.g. fleet, etcd, flannel, etc..) that the coreos guys write on top of the base OS to make it more cloud centric and usable but the core of the OS is very bare bones.

https://coreos.com/using-coreos/

**Comment by Blackglade** [comment]
@darealshinji While CoreOs doesn't have a package manager (as you're supposed to put all your applications in virtualized containers), there is a way to install packages using a startup script that you can tell your OS to run when it first starts up. (Not sure if that's helpful.)

You can find more about it here:
https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting
Skip  To: Update or Install Packages on the Server

**Comment by darealshinji** [comment]
Does [this](https://github.com/darealshinji/screenFetch/tree/CoreOS) version properly detect CoreOS + release name and version?

**Comment by cdancy** [comment]
Closing as coreos is now dead and has been absorbed by red hat.

**Comment by haximilian** [comment]
@cdancy @darealshinji Container Linux ("CoreOS" is the company, "Container Linux" is the Operating System) is, in fact, not dead (see [this](https://news.ycombinator.com/item?id=16292386) post) but rather the company which produced it has simply been acquired by RedHat. I would like to request that this issue be reopened, as I would like very much to have screenFetch functionality on my Container Linux hosts.

**Comment by cdancy** [comment]
@haximilian that's true but technically out of date. RedHat has been acquired by IBM recently and so I have to imagine _may_ have various brandings re-done.

**Comment by haximilian** [comment]
@cdancy Thank you for your correction. Nonetheless, I feel it to be a bit premature to declare Container Linux dead.

**Comment by cdancy** [comment]
Not dead just absorbed by redhat and most likely under a new moniker
