### ISSUE TITLE
CPU frequency not recognized as integer

### ISSUE THREAD

**Issue by arbolis** [KittyKatt/screenFetch#254]
I've just updated to the latest git version of screenfetch (in Arch Linux) and a bug I had been told was fixed in the git version doesn't seem to be fixed.
Whenever I start screenfetch I get the message : "/usr/bin/screenfetch: line 817: [: 2415.7: integer expression expected".
It seems to be caused because the frequency of my processor is not very common (CPU: Intel Celeron CPU N2830 @ 2415.7MHz) and screenfetch wasn't designed to deal with such frequencies.

**Comment by bmwiedemann** [comment]
This was already fixed by db08ebc2a9a7ec75e4b88a585415136433fa3b0c

**Comment by KittyKatt** [comment]
@arbolis Can you confirm that this is what you were asking about?

**Comment by arbolis** [comment]
Yes, the latest update in Arch Linux fixed the problem so I guess bmwiedmann is right. I can confirm the problem is gone.
