### ISSUE TITLE
Debian testing gtk, icon, font not found

### ISSUE THREAD

**Issue by mudongliang** [KittyKatt/screenFetch#257]
I get the result in the following picture in which gtk icon font not found ,but gtk, icon, font actually exists in the 2th and 3th picture.
![screenshot from 2015-07-17 16-55-10](https://cloud.githubusercontent.com/assets/6214861/8743811/bfe6a7f4-2ca4-11e5-84f7-3bb261ecd628.png)
![screenshot from 2015-07-17 16-55-47](https://cloud.githubusercontent.com/assets/6214861/8743815/c413b27c-2ca4-11e5-98a0-ced19c812547.png)
![screenshot from 2015-07-17 16-55-58](https://cloud.githubusercontent.com/assets/6214861/8743819/c7599f0a-2ca4-11e5-880e-1e161bb03699.png)

**Comment by mudongliang** [comment]
debian stable has the same question!

**Comment by gatheringdust** [comment]
Same on Fedora 22 Workstation
![ss 2015-07-18 at 09 23 39](https://cloud.githubusercontent.com/assets/11861221/8761401/9066a49e-2d93-11e5-9782-183620794bf0.png)
![9j3vrym](https://cloud.githubusercontent.com/assets/11861221/8761402/98787a2c-2d93-11e5-875e-adc6a4041c38.png)
![rh4qjkt](https://cloud.githubusercontent.com/assets/11861221/8761403/9c470722-2d93-11e5-94f2-83f7797522ad.png)

**Comment by mudongliang** [comment]
My screenfetch is installed from the default mirror, but when I download the screenfetch-dev
I found  it can detect my gtk, icon,font
@gatheringdust you can test it again.

**Comment by gatheringdust** [comment]
screenfetch-dev works as expected

**Comment by GLolol** [comment]
Debian stable, testing, and Fedora 22 all seem to have screenfetch v3.6.5 in their repositories, and a lot has changed since then: https://github.com/KittyKatt/screenFetch/compare/v3.6.5...master

#170 seems to be the fix in question.

**Comment by gatheringdust** [comment]
Thanks for doing the digging @GLolol I'll stick to the latest version for now.
