### ISSUE TITLE
Who's connected

### ISSUE THREAD

**Issue by nothing-fr** [KittyKatt/screenFetch#258]
Is it possible to add the number of connected users (ssh) to Screenfetch ?

Something like this :

```

                                           root@mymachine
              `.-..........`               OS: Red Hat Enterprise Linux 
             `////////::.`-/.              Kernel: x86_64 Linux 3.10.0-229.4.2.el7.x86_64
             -: ....-////////.             Uptime: 65d 1h 13m
             //:-::///////////`            Packages: 592
      `--::: `-://////////////:            Shell: bash 4.2.46
      //////-    ``.-:///////// .`         CPU: 2x Intel Xeon CPU E5620 @ 2.394GHz
      `://////:-.`    :///////::///:`      RAM: 1756MiB / 3788MiB
        .-/////////:---/////////////:      CONNECTED USERS: 2
           .-://////////////////////.        - root (pts/0) from 10.100.6.0 on 2015-07-26 23:46
          yMN+`.-::///////////////-`         - fred (pts/1) from 10.100.6.3 on 2015-07-27 00:01   
       .-`:NMMNMs`  `..-------..`         
        MN+/mMMMMMhoooyysshsss            
 MMM    MMMMMMMMMMMMMMyyddMMM+            
  MMMM   MMMMMMMMMMMMMNdyNMMh`     hyhMMM 
   MMMMMMMMMMMMMMMMyoNNNMMM+.   MMMMMMMM  
    MMNMMMNNMMMMMNM+ mhsMNyyyyMNMMMMsMM   

```

**Comment by MichaelVessia** [comment]
I would expect it's possible using the output of either `w`, `who`, or `netstat`.  

Some more details can be found here: 
http://unix.stackexchange.com/questions/92560/list-all-connected-ssh-sessions.

**Comment by Kattus** [comment]
A better output would be something like `USERS: root, fred` imo

**Comment by nothing-fr** [comment]
I've made it since the last time, sorry i've forget to update this issue :

printf "\n${PINK}███ LOGGED USERS ███${D}\n"
who | sed "s/(//g" | sed "s/)//g" | awk '{
if ($5 =="") print "  User: "$1"\n    Terminal: "$2"\n    Connected since: " $3" "$4"\n    Connected from: N/A";
else
print "  User: "$1"\n    Terminal: "$2"\n    Connected since: " $3" "$4"\n    Connected from: "$5;
}'

Render :

**Comment by KittyKatt** [comment]
That last script is a LOT of vertical space. Something I'll consider, but maybe not in that format.

**Comment by KittyKatt** [comment]
Closed as I don't think this really falls under the scope of screenfetch.
