### ISSUE TITLE
dconf error without sudo

### ISSUE THREAD

**Issue by Joker701** [KittyKatt/screenFetch#262]
I'm on Debian sid, and that may be the issue but when running the program as my regular user I get the following error, if run with sudo, it works as designed but the shell, icons and theme are misreported due to it being the root users account.
[[ ! ]] 
[[ ! ]] (process:20718): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': 
Permission denied.  dconf will not work properly.
[[ ! ]] 
[[ ! ]] (process:20719): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.
[[ ! ]] 
[[ ! ]] (process:20720): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.

**Comment by GLolol** [comment]
Possibly related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=732209?

**Comment by Joker701** [comment]
Thanks, that was it, I added my user to the root group and it solved the 
problem.
Have a great day.
-F

**Comment by KittyKatt** [comment]
So is this upstream in Debian? Should I close this or is it something that can be easily resolved in a base system?

**Comment by Joker701** [comment]
It appears to be fine now and you can close it, thanks much.
Frank
