### ISSUE TITLE
Disk usage not displaying Mac OSX

### ISSUE THREAD

**Issue by sbdchd** [KittyKatt/screenFetch#276]
Disk usage is not being displayed when using `screenfetch`. 

If this is expected, I am wondering if displaying disk usage could be implemented since disk usage is already included in the program for mac osx.

**Comment by Kattus** [comment]
Disk usage is not displayed by default, did you use `screenfetch -d '+disk'`?

**Comment by sbdchd** [comment]
Oh, I wasn't aware that was an option.

Thanks a bunch!

**Comment by KittyKatt** [comment]
DIsk usage is turned off by default because it is very broken in GNU/Linux systems.
