### ISSUE TITLE
Add support for exherbo Linux

### ISSUE THREAD

**Issue by rtlanceroad** [KittyKatt/screenFetch#280]
The homepage is here: https://www.exherbo.org/

Below is the related info:

lee@sakura ~ $ cat /etc/os-release 
NAME="Exherbo"
PRETTY_NAME="Exherbo Linux"
ID="exherbo"
ANSI_COLOR="0;32"
HOME_URL="https://www.exherbo.org/"
SUPPORT_URL="irc://irc.freenode.net/#exherbo"
BUG_REPORT_URL="https://bugs.exherbo.org/"
lee@sakura ~ $ cat /etc/issue 

This is \n.\O (\s \m \r) \t

Thanks for implemention. : - )

**Comment by darealshinji** [comment]
Okay, I'll give it a try.

What's the output of `lsb_release -sirc`?
Are there any other `/etc/*-release` files besides `/etc/os-release`? And if yes, what's their content?
How does one list the amount of installed packages? On Gentoo it's `ls -d /var/db/pkg/*/* | wc -l`, does that work for Exherbo too?
Is there a VirtualDisk image somewhere available for quick testing?

**Comment by rtlanceroad** [comment]
@darealshinji ty. Currently I don't have exherbo machines around. But afair there is no lsb_release or /etc/*-release(besides /etc/os-release) file.

**Comment by darealshinji** [comment]
I've tried to bootstrap the system, but I can't get it really to work. Anyway, the current stage tarballs seem to be missing `/etc/os-release` but instead there's `/etc/exherbo-release` now.
Here's my attempt to support it: https://github.com/darealshinji/screenFetch/commit/07345579c7c7bd42d3e23ea1c8c997df1c20b968
I don't know if the package detection is 100% correct though, and the ASCII logo might need some fine-tuning.

**Comment by KittyKatt** [comment]
Will look at this again soon. Need to look at what @darealshinji is doing in his commit. He may have the right idea.

**Comment by darealshinji** [comment]
Exherbo detection was added. I'm closing it now, okay?
