### ISSUE TITLE
revise alignment of the output information of antergos

### ISSUE THREAD

**Issue by mudongliang** [KittyKatt/screenFetch#284]
![screenshot from 2015-09-21 00-09-11](https://cloud.githubusercontent.com/assets/6214861/9981649/0a1b5ac6-5ff5-11e5-82bd-f3640fbeac6d.png)
RAM is not at right position.
I find it in the source code , 
      
      "${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms. %s"

and I want to just add a space to solve this problem ,but it not works!

      "${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms.  %s"

How should I revise the alignment?

**Comment by darealshinji** [comment]
Adding a space in that line and removing one in the line below fixed it for me.
``` diff
--- bin/screenfetch_	2015-09-20 20:59:39.645497700 +0200
+++ bin/screenfetch	2015-09-20 20:59:57.460430300 +0200
@@ -3739,8 +3739,8 @@
 "${c1}ddmmdddddhhhhhhhso${c2}++++++${c1}yhhhhhhdddddmmdy %s"
 "${c1}dmmmdddddddhhhyso${c2}++++++${c1}shhhhhddddddmmmmh %s"
 "${c1}-dmmmdddddddhhys${c2}o++++o${c1}shhhhdddddddmmmmd- %s"
-"${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms. %s"
-"${c1}   \`+ydmmmdddddddddddddddddddmmmmdy/.     %s"
+"${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms.  %s"
+"${c1}   \`+ydmmmdddddddddddddddddddmmmmdy/.    %s"
 "${c1}      \`.:+ooyyddddddddddddyyso+:.\`")
 		;;
 
```
![screen-2015-09-20_21-02](https://cloud.githubusercontent.com/assets/5700937/9982395/491c7ddc-5fdb-11e5-8106-3e4991f86fe3.png)

But I've tested it only in msys2 with `-A 'Antergos'` (ignore the 'djcj@djcj-PC' lines).

**Comment by mudongliang** [comment]
diff --git a/screenfetch-dev b/screenfetch-dev
    index 729a234..d395610 100755
    --- a/screenfetch-dev
    +++ b/screenfetch-dev
    @@ -3753,8 +3753,8 @@ asciiText () {
    "${c1}ddmmdddddhhhhhhhso${c2}++++++${c1}yhhhhhhdddddmmdy %s"
    "${c1}dmmmdddddddhhhyso${c2}++++++${c1}shhhhhddddddmmmmh %s"
    "${c1}-dmmmdddddddhhys${c2}o++++o${c1}shhhhdddddddmmmmd- %s"
    -"${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms. %s"
    -"${c1}   \`+ydmmmdddddddddddddddddddmmmmdy/.     %s"
    +"${c1} .smmmmddddddddhhhhhhhhhdddddddddmmmms.  %s"
    +"${c1}   \`+ydmmmdddddddddddddddddddmmmmdy/.    %s"
     "${c1}      \`.:+ooyyddddddddddddyyso+:.\`")
                    ;;

I do as you said, but it not works. Same as before.

**Comment by mudongliang** [comment]
screenfetch in community(archlinux) has this problem, but it doesn't occur in the latest source code in github. I will report bug to archlinux.
Thank you.
