### ISSUE TITLE
Screenfetch not detecting DE, themes, or fonts

### ISSUE THREAD

**Issue by fhdj345** [KittyKatt/screenFetch#285]
Hello, I recently installed screenfetch on Debian Stable with XFCE, and I noticed that it displays "Not Found" or "Not Present" for the desktop environment, GTK themes, icon theme, and font.
However, it is seemingly displaying the WM theme as it should. 
I have set themes and font in Settings>Appearance>Style, Icons, and Font, but screenfetch is telling me it cannot find them.
What could the problem be?
Here is a screenshot of the verbose output.
![screenshot - 09192015 - 10 07 59 pm](https://cloud.githubusercontent.com/assets/14381664/9982228/d6cf019c-5fa2-11e5-8728-53fea34646e3.png)

**Comment by shiba89** [comment]
@fhdj345 I had the same problem in 3.6.5, seems to be fixed in 3.7.0 (wrongly labeled 3.6.8 with -V)

![schermata da 2016-01-08 10-23-54](https://cloud.githubusercontent.com/assets/3816409/12194764/92422b3e-b5f2-11e5-883a-e22de0e76864.png)

**Comment by KittyKatt** [comment]
Looks fixed? Not sure for the OP but it's 4 years old at this point, so gonna assume fixed.
