### ISSUE TITLE
Add support for SailfishOS

### ISSUE THREAD

**Issue by PureTryOut** [KittyKatt/screenFetch#286]
Sailfish homepage: https://sailfishos.org

SailfishOS is a Linux distribution for the mobile phone and tablets. Currently only official supported on the Jolla Phone, a phone from an Indian manufacturer and soon the Jolla Tablet, but has lots of unofficial ports to other devices such as the Nexus series.

Screenfetch currently runs fine (cloned the git repo and ran screenfetch-dev) but shows the standard Tux logo, and has no clue how many packages are installed.

It uses the "pkcon" package manager, which is RPM based.

If I need to include other information, don't hesitate to ask.

**Comment by darealshinji** [comment]
Adding support should be easy. If it's RPM-based, listing packages should work with `rpm -qa | wc -l`.
What's the output of
``` sh
lsb_release -sirc
cat /etc/os-release
cat /etc/issue
```
?

**Comment by PureTryOut** [comment]
```lsb_release -sirc = Mer 0.2011 Mer
cat /etc/os-release = NAME=SailfishOS
ID=sailfishos
VERSION="1.1.7.28 (Björnträsket) (armv7hl)"
VERSION_ID=1.1.7.28
PRETTY_NAME="SailfishOS 1.1.7.28 (Björnträsket) (armv7hl)"
SAILFISH_BUILD=28
SAILFISH_FLAVOUR=release
HOME_URL="https://sailfishos.org/"

cat /etc/issue = Mer release 0.2011 (Mer)
Kernel \r on an \m```

**Comment by darealshinji** [comment]
https://github.com/darealshinji/screenFetch/blob/SailfishOS/screenfetch-dev
Does this version detect it correctly?

**Comment by PureTryOut** [comment]
It shows the correct amount of packages yes. Except for that, nothing changed (although I'm guessing that is expected).

**Comment by darealshinji** [comment]
I've added a logo.
https://github.com/darealshinji/screenFetch/blob/SailfishOS/screenfetch-dev

**Comment by PureTryOut** [comment]
Works great!
https://u.teknik.io/LTrw0h.jpg

**Comment by darealshinji** [comment]
It shouldn't display "SailfishOS" in the OS line twice though. And the shell isn't detected correctly either. Can you show the output of `./screenfetch-dev -v`?

**Comment by PureTryOut** [comment]
```
:: Finding distro...found as 'SailfishOS 0.2011'
:: Finding hostname and user...found as 'nemo@'
:: Finding kernel version...found as 'armv7l Linux 3.4.106.20150416.1'
:: Finding current uptime...found as '6h 43m'
:: Finding current package count...found as '701'
:: Finding current shell...found as '15075'
:: Finding current resolution(s)...found as ''
:: Finding desktop environment...found as 'Not Present'
:: Finding window manager...found as 'Not Found'
:: Finding window manager theme...found as 'Not Found'
:: Finding GTK2 theme...found as 'Not Found'
:: Finding GTK3 theme...found as 'Not Found'
:: Finding icon theme...found as 'Not Found'
:: Finding user font...found as 'Not Found'
:: Finding current CPU...found as 'QCT MSM8930 CDP @ 1.404GHz'
:: Finding current GPU...found as 'Not Found'
:: Finding current RAM usage...found as '530MiB / 809MiB'
              .+eWWW             nemo@
          .+ee+++eee      e.     OS: sailfishos SailfishOS 0.2011 Mer
       .ee++eeeeeeee    +e.      Kernel: armv7l Linux 3.4.106.20150416.1
     .e++ee++eeeeeee+eee+e+      Uptime: 6h 43m
    ee.e+.ee+eee++eeeeee+        Packages: 701
   W.+e.e+.e++ee+eee             Shell: 15075
  W.+e.W.ee.W++ee'               CPU: QCT MSM8930 CDP @ 1.404GHz
 +e.W W.e+.W.W+                  RAM: 530MiB / 809MiB
 W.e.+e.W W W.                  
 e e e +e.W.W                   
       .W W W.                  
        W.+e.W.                 
         W++e.ee+.              
          ++ +ee++eeeee++.      
          '     '+++e   'ee.    
                           ee   
                            ee  
                             e  
```

**Comment by darealshinji** [comment]
I've updated the script. I hope it'll now display the OS name once, as well as the correct version (1.1.7.28) and the codename.

**Comment by PureTryOut** [comment]
Nope, same results sadly...

**Comment by darealshinji** [comment]
Should I still make a pull request?

**Comment by PureTryOut** [comment]
You're asking me? Sure, this is still much better then the original result!

**Comment by darealshinji** [comment]
SailfishOS was added.
