### ISSUE TITLE
Displaying wrong DE when using Marco

### ISSUE THREAD

**Issue by DougTy** [KittyKatt/screenFetch#287]
Using XFCE4 as DE and Marco for WM, screenfetch is incorrectly listing my DE as MATE.
If I comment out [this chunk](https://github.com/KittyKatt/screenFetch/blob/75676330651dc39acdc077bcecd1562e370fedce/screenfetch-dev#L1330), then the DE is correctly listed as XFCE4.

```
else if ($1 ~ /^_MARCO/) {
	de = "MATE"
	exit
}
```

I know this is probably a rare combination. GTK and icon themes also come in as incorrect when it thinks MATE is my DE, but after commenting out the above and it correctly detecting XFCE, everything is fine.

**Comment by v0idpwn** [comment]
Can somebody please check if it still detects Mate correctly if this line is commented?
I dont understand the real need of this part of the code.

**Comment by darealshinji** [comment]
MATE is still detected for me on Ubuntu 16.04.
