### ISSUE TITLE
screenfetch -L changes the color of the bash prompt afterwards

### ISSUE THREAD

**Issue by fturco** [KittyKatt/screenFetch#289]
On my system the command `screenfetch -L` changes the color of the bash prompt afterwards, from white to fucsia. My distro is Parabola GNU/Linux-libre and I'm using the git version (3.7.0.r22.ga86ce5e-1).
![screenfetch-l](https://cloud.githubusercontent.com/assets/5459866/10124880/af2564aa-6561-11e5-8423-653378170409.png)

**Comment by Kattus** [comment]
![Confirmed on Arch](http://i.imgur.com/IM7Ux5q.png)
Just confirming for Arch Linux, doesn't happen when using another shell than bash though.

**Comment by darealshinji** [comment]
Weird, I don't have this issue on Ubuntu.
Does this patch fix this issue for you?
``` diff
--- screenfetch	2015-09-28 07:27:17.761811372 +0200
+++ screenfetch_	2015-09-28 07:25:27.585809000 +0200
@@ -3966,7 +3966,7 @@
 
 	elif [[ "$display_logo" == "Yes" ]]; then
 		for ((i=0; i<${#fulloutput[*]}; i++)); do
-			printf "${fulloutput[i]}\n"
+			printf "${fulloutput[i]}${c0}\n"
 		done
 
 	else
```

**Comment by fturco** [comment]
Your patch fixes the problem in my case. Anyway I forgot to say that I am using bash and GNOME Terminal.
