### ISSUE TITLE
screenfetch -n doesn't display my GTK theme correctly

### ISSUE THREAD

**Issue by fturco** [KittyKatt/screenFetch#290]
On my system the `screenfetch -n` command doesn't display my GTK theme correctly:

![screenfetch-n](https://cloud.githubusercontent.com/assets/5459866/10124886/de1681fe-6561-11e5-8f5c-ec18d9fa8258.png)

It is true that I'm using Adwaita, but it is not nice that screenfetch displays that on two lines without a proper header.

My distro is Parabola GNU/Linux-libre and I'm using the git version (3.7.0.r22.ga86ce5e-1).

**Comment by Kattus** [comment]
[Confirmed on Arch Linux](http://i.imgur.com/IM7Ux5q.png)
Just confirming on Arch Linux, doesn't happen when using another shell than bash though.

**Comment by Kattus** [comment]
Non-ASCII mode (-n) is known broken.

**Comment by darealshinji** [comment]
![gtktheme](https://cloud.githubusercontent.com/assets/5700937/15090852/a72c4276-1436-11e6-9aab-533b8fcd4e6b.png)
Fixed. It _should_ also be displayed correctly when GTK2 and GTK3 themes are different, but testing that on Ubuntu is very difficult (there are no options here to set the themes for gtk2 and 3 independently).
