### ISSUE TITLE
Non-working awk expression for "gtkIcons" detection with ROX-Filer Options

### ISSUE THREAD

**Issue by Flashwalker** [KittyKatt/screenFetch#292]
"**${XDG_CONFIG_HOME:-${HOME}/.config}/rox.sourceforge.net/ROX-Filer/Options**" file contents:

```
...
  <Option name="icon_theme">evolvere-black-folders-vivid-dark-fallback</Option>
...
```
for "**icon_theme**", and:

```
gtkIcons=$(awk -F'[>,<]' '/^icon_theme/ {print $3}' ${XDG_CONFIG_HOME:-${HOME}/.config}/rox.sourceforge.net/ROX-Filer/Options)
```
returns nothing, but:

```
gtkIcons=$(awk -F'[>,<]' '/icon_theme/ {print $3}' ${XDG_CONFIG_HOME:-${HOME}/.config}/rox.sourceforge.net/ROX-Filer/Options)
```
without "**^**" works fine.

**Comment by darealshinji** [comment]
Was changed at some point: https://github.com/KittyKatt/screenFetch/blob/acfb35173ba8ba6eb6b191f402c6d68cf0e15b2d/screenfetch-dev#L2204
So I'm closing it.
