### ISSUE TITLE
Support for sway

### ISSUE THREAD

**Issue by SethBarberee** [KittyKatt/screenFetch#305]
Hi, I am having a problem with screenfetch when I run it inside sway. In the output, it says xwlc when it really should be sway. I didn't know whether to ask here or on the sway issues so I asked you. If you have a fix, then that would be appreciated! Thanks for an awesome program!

**Comment by 4e554c4c** [comment]
It looks to me like this is because if a WM is not listed in wmnames, which sway isn't, screenfetch asks xprop what the WM is, and since sway runs on wayland xprop can't figure in out. So it says xwlc (XWayLand Compositor?).

**Comment by SethBarberee** [comment]
So are you suggesting to add sway to wmnames? If so, I can fork the repository and work on that.

**Comment by 4e554c4c** [comment]
I already added a fork that did so. A real fix would be to add a detection for Wayland WMs, but that's beyond what I know.

**Comment by SethBarberee** [comment]
I'll test your fork and I should have some feedback in the next day or two

**Comment by SethBarberee** [comment]
Fixed with pull request cbdbd179320269f5e75dc3fe32aae56d63cdd944

**Comment by 4e554c4c** [comment]
I wouldn't close this issue yet because cbdbd17 hasn't been pulled.
