### ISSUE TITLE
Issue on RedHat Enterprise Linux (RHEL)

### ISSUE THREAD

**Issue by nrechn** [KittyKatt/screenFetch#308]
Here is an issue on running screenfetch in RHEL. The output is the lovely Tux instead of RedHat logo. 

I have to modify `/etc/os-release` file in order to let output be correct. It will only work (display  RedHat logo) if I edit `ID="rhel"` to `ID="Red Hat Enterprise Linux"` . 
(The original "os-release" file shows the ID is 'rhel')

Therefore, it seems that something wrong on detecting `ID=   ` in  `/etc/os-release` .

**Comment by nickbean01** [comment]
Which version are you running? I'm on 6.4 here at work and it behaves correctly.

**Comment by nrechn** [comment]
I am on RHEL 7.0. It probably doesn't work on 7.1 and 7.2 as well.

**Comment by darealshinji** [comment]
Does [this](https://github.com/KittyKatt/screenFetch/commit/c5cab3d6cfba14d460a7e918a987ebd934a845d5) commit fix it?
Also, is `/etc/system-release` present and if yes, what's its content?

**Comment by nrechn** [comment]
Thanks. It is fixed. Sorry for late response.
