### ISSUE TITLE
Easter egg: Resident Evil 

### ISSUE THREAD

**Issue by Saphyel** [KittyKatt/screenFetch#310]
Hello I was thinking could be cool add something like [Umbrella unix with the umbrella logo](http://i.imgur.com/mLftARM.jpg)

**Comment by darealshinji** [comment]
Like this?

![bildschirmfoto vom 2015-12-26 13 47 52](https://cloud.githubusercontent.com/assets/5700937/12006430/4b948012-abd7-11e5-98d1-7e5a59df3d97.png)

https://github.com/darealshinji/screenFetch/tree/umbrella
Might not work correctly on non-Linux systems.

**Comment by Saphyel** [comment]
@darealshinji yay! you complete read my mind! *_*

**Comment by darealshinji** [comment]
I don't think this should be part of the official sF script, so I'm closing it.
You can always find a .diff and a patched script here:
https://gist.github.com/darealshinji/ddefefb30ffa56c17e3e691fcb3d2167
