### ISSUE TITLE
GPU detect lines cause errors in OpenBSD

### ISSUE THREAD

**Issue by Head-on-a-Stick** [KittyKatt/screenFetch#312]
I have two laptops with Intel integrated graphics cards (Ironlake & Haswell) running OpenBSD *-current* 

The script throws up an error on lines 1069 & 1073:

`[[ ! ]] sed: 1: "1h;2,$H;${g;s/
/,/g;p}": extra characters at the end of p command`

This would suggest that OpenBSD is being mis-identified as "Mac OS X" but only in the GPU section, the "OS:" line is correct.

If the two lines are removed, the script runs without error but the GPU line is omitted.

**Comment by darealshinji** [comment]
Does this fix it? https://github.com/KittyKatt/screenFetch/pull/307

**Comment by Head-on-a-Stick** [comment]
Yes it does!

Thank you very much :)
