### ISSUE TITLE
vesion 3.7.0 displays wrong version number

### ISSUE THREAD

**Issue by jhelfman** [KittyKatt/screenFetch#316]
[/usr/home/helfman/Downloads/screenFetch-3.7.0]$ ./screenfetch-dev --version
screenFetch - Version 3.6.8
Created by and licensed to Brett Bohnenkamper <kittykatt@kittykatt.us>
OS X porting done almost solely by shrx (https://github.com/shrx) and John D. Duncan, III (https://github.com/JohnDDuncanIII).

This is free software; see the source for copying conditions.  There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jhelfman** [comment]
Here is a patch to update the version.

[patch-screenfetch-dev.txt](https://github.com/KittyKatt/screenFetch/files/143553/patch-screenfetch-dev.txt)

**Comment by darealshinji** [comment]
Fixed.
