### ISSUE TITLE
Unknown OS on Raspberry Pi

### ISSUE THREAD

**Issue by ravkr** [KittyKatt/screenFetch#317]
screenfetch shows `OS: Unknown 8.0 jessie` on Raspberry Pi 2 running Raspbian.
![screenshot](https://cloud.githubusercontent.com/assets/3875202/12377561/2d00eee0-bd22-11e5-8d18-a2a86db3d28b.png)

---

when using development version it shows `OS: raspbian Raspbian 8.0 jessie`
![zrzut ekranu z 2016-01-17 14 23 24](https://cloud.githubusercontent.com/assets/3875202/12377671/0e456446-bd26-11e5-808c-42d46d735181.png)

**Comment by Kattus** [comment]
The one in Debian repo is outdated, and the development version shows exactly what it shows for other distros.  What's the problem?

**Comment by darealshinji** [comment]
Does the latest version work correctly?

**Comment by ravkr** [comment]
everything is fine now ;)
![zrzut ekranu z 2016-05-10 14 49 03](https://cloud.githubusercontent.com/assets/3875202/15147005/6bd9d672-16be-11e6-8f18-be6ec806df91.png)
