### ISSUE TITLE
FreeBSD packaging covers screenfetch installation

### ISSUE THREAD

**Issue by jhelfman** [KittyKatt/screenFetch#319]
FreeBSD can install via the ports system, however we do also offer packages like many other operating systems.

pkg install screenfetch

Can you please update the documentation?

**Comment by darealshinji** [comment]
https://github.com/KittyKatt/screenFetch#freebsd
Is it okay like that?

**Comment by jhelfman** [comment]
Sure, however the note about bash should include the package too if you are
going to keep that portion.

pkg install bash

And to e-mail the port maintainer --- since you had mentioned if there is a
problem with the package.

Thanks!

jgh

On Fri, May 6, 2016 at 8:03 PM, darealshinji <notifications@github.com>
wrote:

> https://github.com/KittyKatt/screenFetch#freebsd
> Is it okay like that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KittyKatt/screenFetch/issues/319#issuecomment-217601799>
>



-- 
Jason Helfman          | FreeBSD Committer
jgh@FreeBSD.org     | http://people.freebsd.org/~jgh  | The Power to Serve

**Comment by darealshinji** [comment]
The last time I tried sF on FreeBSD I got an output like that in the first post: https://github.com/KittyKatt/screenFetch/issues/339
Installing or re-installing bash through the packages didn't fix it. After I installed bash from the ports it worked however. Not really sure what the problem was.

**Comment by jhelfman** [comment]
Seems like that error is in Linux, and not FreeBSD, from the output of
uname. Is that correct?
-jgh

On Fri, May 6, 2016 at 8:45 PM, darealshinji <notifications@github.com>
wrote:

> The last time I tried sF on FreeBSD I got an output like that in the first
> post: #339 <https://github.com/KittyKatt/screenFetch/issues/339>
> Installing or re-installing bash through the packages didn't fix it. After
> I installed bash from the ports it worked however. Not really sure what the
> problem was.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KittyKatt/screenFetch/issues/319#issuecomment-217603783>
>



-- 
Jason Helfman          | FreeBSD Committer
jgh@FreeBSD.org     | http://people.freebsd.org/~jgh  | The Power to Serve

**Comment by darealshinji** [comment]
Yes, but the last time I tried the script on FreeBSD IIRC I had the same or a similar output. And for some reason this was only fixed by installing bash from the ports instead of the packages.

**Comment by jhelfman** [comment]
Installing ports vs. packages will always be unreliable, as packages are
built in a jail. Ports are not, and are subject to local configuration and
library conflicts.  Chances are there was a local issue, or there was an
issue with the package version you were installing.

Either way, the solution may be to re-install bash, however that indicates
there is another problem that should be addressed.  The user should submit
a problem report to FreeBSD for this at
https://www.freebsd.org/support/bugreports.html

The end result of building a port is a package.  So when you install the
port, it registers as a package, and is supported by all of the toolset on
FreeBSD for packages/ports.

HTH
-jgh

On Fri, May 6, 2016 at 8:56 PM, darealshinji <notifications@github.com>
wrote:

> Yes, but the last time I tried the script on FreeBSD IIRC I had the same
> or a similar output. And for some reason this was only fixed by installing
> bash from the ports instead of the packages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KittyKatt/screenFetch/issues/319#issuecomment-217604653>
>



-- 
Jason Helfman          | FreeBSD Committer
jgh@FreeBSD.org     | http://people.freebsd.org/~jgh  | The Power to Serve

**Comment by darealshinji** [comment]
I've updated the description.
