### ISSUE TITLE
kali rolling shows duplicate on os name

### ISSUE THREAD

**Issue by fhoshino** [KittyKatt/screenFetch#321]
![conemu64_2016-01-27_22-06-56](https://cloud.githubusercontent.com/assets/771955/12615719/52ce0d24-c542-11e5-8232-cd4b3f0b433a.png)
OS name shows as "kali linux Kali Linux kali-rolling kali-rolling"

**Comment by darealshinji** [comment]
Should be fixed now.

**Comment by fhoshino** [comment]
![conemu64_2016-05-06_22-08-43](https://cloud.githubusercontent.com/assets/771955/15075477/256d951e-13d7-11e6-94e4-a5f3d04f4740.png)
Seems not.

**Comment by darealshinji** [comment]
Kali is always a rolling release distro, right?

**Comment by fhoshino** [comment]
After 2.0, seems yes.

**Comment by darealshinji** [comment]
Does the version from [this](https://github.com/darealshinji/screenFetch/tree/kali) branch work correctly?

**Comment by fhoshino** [comment]
![tmp_18058-screenshot_2016-05-07-01-19-57-1991117296](https://cloud.githubusercontent.com/assets/771955/15080782/4bc5bece-13f2-11e6-93c8-3b6893f39759.png)
it works.

**Comment by darealshinji** [comment]
Fixed in https://github.com/KittyKatt/screenFetch/commit/24359a1f8d351a35603cbf250fa80153fa152716
