### ISSUE TITLE
KWin 5 theme detect.

### ISSUE THREAD

**Issue by s8321414** [KittyKatt/screenFetch#326]
KWin 5's theme should be in following location:

> [org.kde.kdecoration2]
> library=org.kde.breeze (this name is an example, may be this or org.kde.oxygen or any other name like this)

**Comment by darealshinji** [comment]
Which file is storing this information?

**Comment by s8321414** [comment]
@darealshinji in .config/kwinrc , but I don't know if it's hard-coded...

**Comment by darealshinji** [comment]
I checked a Kubuntu Live DVD. The theme name appeared for me only after I've changed the theme settings for the first time. This is the content of `~/.config/kwinrc`:
```
[Compositing]
Backend=XRender
OpenGLIsUnsafe=false

[Desktops]
Number=1

[TabBox]
DesktopLayout=org.kde.breeze.desktop
DesktopListLayout=org.kde.breeze.desktop
LayoutName=org.kde.breeze.desktop
```
I'll try to figure out a more reliable method.

**Comment by darealshinji** [comment]
It looks like in `~/.config/kwinrc` there's only the widget theme saved but not the general DE theme. That is saved in `$KDE_CONFIG_DIR/share/config/kdeglobals` for me. I hope it's now fixed.

**Comment by darealshinji** [comment]
Does it now work correctly for you?

**Comment by s8321414** [comment]
hmm... I got my Desktop Theme in WM theme section, don't know if it's correct behaviour.

**Comment by s8321414** [comment]
And Kubuntu 16.04 use KF5/Plasma5 not?!

**Comment by darealshinji** [comment]
> hmm... I got my Desktop Theme in WM theme section, don't know if it's correct behaviour.

There's no "DE Theme" section, so yes, it seems to be correct.

> And Kubuntu 16.04 use KF5/Plasma5 not?!

Will check again.

**Comment by darealshinji** [comment]
Kubuntu 16.04 is using KDE 5 and theme detection works there.

**Comment by s8321414** [comment]
@darealshinji Thanks!
