### ISSUE TITLE
GPU isn't showing in Arch Linux

### ISSUE THREAD

**Issue by zoutiyx** [KittyKatt/screenFetch#335]
This is the output of the `screenfetch`:

![AL screenfetch](http://s10.postimg.org/mrplij61l/no_gpu.png)

This is the command I use to find my GPU. `lspci -k | grep -A 2 -E "(VGA|3D)" | grep "NVIDIA"`:
**01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 860M] (rev ff)**

If I had knowledge of AWK I would have modified it myself to extract only the GPU info.

**Comment by maotora** [comment]
I have an intel GPU and i did this..
which i'm sure works with every data (as they look similar formatted) 

`lspci -k | grep -A 2 -E "(VGA|3D)" | grep "Intel" | awk -F : '{print $3}' `

with **Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)** As the result.

Which I think one can write it as 
`lspci -k | grep -A 2 -E "(VGA|3D)" | grep -E "(NVIDIA|Intel)" | awk -F : '{print $3}' ` To grep either Nvidia or Intel and show information. 
But i don't really know grep that much either.

**Comment by zoutiyx** [comment]
Ahh. Your implementation seems to get the info. I'm trying to modify the script by adding an if satement to get the GPU for arch. But I'm getting an error. Here is the code:

```
elif [[ "${distro}" == "Arch Linux" ]]; then
        gpu="lspci -k | grep -A 2 -E "(VGA|3D)" | grep -E "(NVIDIA)" | awk -F : '{print $3}'"
    fi
```

I get this error:
syntax error near unexpected token `(' `		gpu="lspci -k | grep -A 2 -E "(VGA|3D)" | grep -E "(NVIDIA)" | awk -F : '{print $3}'"'

Any ideas how I can fix this?

**Comment by KittyKatt** [comment]
Pretty old at this point. If anyone in this thread is still having this issue, please open a new ticket. Thank you.
