### ISSUE TITLE
Screenfetch incorrectly calculates disk size on boxes with Docker containers (aufs/tmpfs)

### ISSUE THREAD

**Issue by svenvandescheur** [KittyKatt/screenFetch#336]
I run screenFetch on a DigitalOcean box with 40GB of disk space. However, according to screenFetch I have 160GB in total. I'd love the free space but unfortunately this is a wrong calculation.

I believe this is is called by the calculation that is used for non-BSD/Mac systems:

    totaldisk=$(df -h --total 2>/dev/null | tail -1)

This doesn't exclude any filesystems that don't eat up space, (like aufs and tmpfs). The filesystems are added tot the total resulting in incorrect numbers.

I would suggest changing this line to:

    df -h -x aufs -x tmpfs --total 2>/dev/null | tail -1

As this will exclude aufs and tmpfs from the calculation.

**Comment by darealshinji** [comment]
Closing it, since the changes from https://github.com/KittyKatt/screenFetch/pull/337 were added.
