### ISSUE TITLE
Add support for windows 10 bash

### ISSUE THREAD

**Issue by runebaas** [KittyKatt/screenFetch#339]
Like the title says, microsoft added bash to windows 10 and running screenfetch results in the following

![like this](http://i.imgur.com/HMhD6XS.png)

**Comment by darealshinji** [comment]
What's the output of `uname -a`? I read that it's actually a kind of virtualized minimum build of Ubuntu running native Linux binaries.

**Comment by runebaas** [comment]
this is the output
Linux localhost 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

the best way to imagine what it is,is cygwin on steroids

**Comment by darealshinji** [comment]
Does adding `fdesc	/dev/fd		fdescfs		rw	0	0` to `/etc/fstab` fix the error messages?
1-liner: `echo "fdesc	/dev/fd		fdescfs		rw	0	0" | sudo tee -a /etc/fstab`

**Comment by darealshinji** [comment]
Ubuntu on Windows support added in commit https://github.com/KittyKatt/screenFetch/commit/d162f5befb8532e78c3c6b2a03bb3c2df1cff417
