### ISSUE TITLE
Add Kali Linux Theme

### ISSUE THREAD

**Issue by AresS31** [KittyKatt/screenFetch#340]
Hi,

I haven't try screenFetch yet so I might be totally wrong but I can see on the description page that there is no dedicated theme for the Kali Linux distribution.
I think that it would be awesome to add a specific theme (including the Kali dragon...) for this distro since it is widely used.

Best,
Alexandre

**Comment by darealshinji** [comment]
Kali Linux is detected and shows the Kali dragon as ASCII logo. Or what do you mean by "theme"?
