### ISSUE TITLE
On windows (cygwin) "Invalid syntax" error for reg query command

### ISSUE THREAD

**Issue by fhoshino** [KittyKatt/screenFetch#349]
![conemu64_2016-05-07_22-16-35](https://cloud.githubusercontent.com/assets/771955/15092613/61a31d7c-14a1-11e6-9d9e-0f62aab62480.png)

**Comment by darealshinji** [comment]
Does it go away if you change the `//v` in line 1957 to `/v`?
```
themeFile="$(reg query 'HKCU\Software\Microsoft\Windows\CurrentVersion\Themes' //v 'CurrentTheme' | grep -o '[A-Z]:\\.*')"
```

**Comment by fhoshino** [comment]
no, the error is still there.

**Comment by fhoshino** [comment]
yes, the error is gone, sorry for the confussion, I just copy the line and didn't notice /v is still //v.

**Comment by darealshinji** [comment]
Okay. On Msys I get the same error when it's `/v` instead of `//v`. Weeeird. Gonna add an additional check.

**Comment by fhoshino** [comment]
confirmed fix

![mintty_2016-05-08_00-05-03](https://cloud.githubusercontent.com/assets/771955/15093135/9a8ec348-14b0-11e6-9f42-01f975beeb66.png)
