### ISSUE TITLE
Add 'KDE neon' distro logo

### ISSUE THREAD

**Issue by darealshinji** [KittyKatt/screenFetch#352]
See http://neon.kde.org/

Distro detection was added, but it's still missing a logo.
I'm not good at creating ASCII arts and the ones created with ASCII generators didn't look good.

**Comment by dylanaraps** [comment]
Hello, 

Feel free to use this kde neon ascii art I made for neofetch.

https://github.com/dylanaraps/neofetch/blob/master/ascii/distro/kde

**Comment by darealshinji** [comment]
That was a quick response.
Thanks. Merged.
