### ISSUE TITLE
something about openSUSE Tumbleweed OS'version

### ISSUE THREAD

**Issue by lipanXJ** [KittyKatt/screenFetch#353]
In screenfetch,the os version is
          OS: Opensuse 20160422 Tumbleweed
  ##########################################################
If i use # cat  /etc/os-release # in terminal,it like this
         NAME=openSUSE
        VERSION="Tumbleweed"
        VERSION_ID="20160512"
        PRETTY_NAME="openSUSE Tumbleweed (20160512) (x86_64)"
############################################################
You could clear see that one is 20160422 while another is 20160512,ISO's version i install is not 20160422 ,and  screenfetch is latest version  from github.Is this a bug  or other?

**Comment by darealshinji** [comment]
What's the output of `lsb_release -sirc`?
And now that I see it, your OS name should be `openSUSE` not `Opensuse`.

**Comment by lipanXJ** [comment]
It return this 
    openSUSE 20160422 Tumbleweed

**Comment by darealshinji** [comment]
Normally a distro release version shouldn't be displayed at all on a rolling release version.
Can you change the part at line 511 like this?
``` sh
"openSUSE"|"openSUSE project"|"SUSE LINUX")
	distro="openSUSE"
	if [[ "${distro_codename}" == "Tumbleweed" ]]; then
		distro_release="n/a"
	fi
	;;
```

**Comment by lipanXJ** [comment]
OK,i see you update screenFetch just now,so i reinstall it ,everything looks fine,and it will return 

OS: openSUSE  Tumbleweed
