### ISSUE TITLE
Getting screen resolution with `wmic desktopmonitor get screenheight, screenwidth` does not work on Windows 10.

### ISSUE THREAD

**Issue by dar-irl** [KittyKatt/screenFetch#354]
Using `wmic desktopmonitor get screenheight, screenwidth` to get the screen resolution doesn't seem to be working on fresh Windows 10 installs, possibly because a fresh Windows 10 install lacks something that Windows 7 would have carried over when upgrading. Could another method of obtaining screen resolution be implemented?

**Comment by dar-irl** [comment]
`wmic path Win32_VideoController get CurrentHorizontalResolution^,CurrentVerticalResolution /value` works correctly.

**Comment by darealshinji** [comment]
Weird, I've never had issues on Windows 10 (I'm using Msys2 though). When you say "fresh install", do you mean the first release version of Windows 10 or do you mean a fresh install of Windows 10 version 15.11 (last year November upgrade)?

**Comment by dylanaraps** [comment]
The command above also doesn't work on my Windows 10 install but works in my Windows XP / 7 VMs. The solution in @dar-irl's second comment works in all three and outputs the exact same info.

My Windows 10 install is from the first release.

**Comment by darealshinji** [comment]
The command `wmic desktopmonitor get screenheight, screenwidth` doesn't actually appear like that in the current script: https://github.com/KittyKatt/screenFetch/blob/156396bef282a53f48973b6cc1398f0bd0aa1b52/screenfetch-dev#L1394

Have you tried the latest version?

**Comment by dar-irl** [comment]
Yeah, it doesn't work on the latest version as well.
`wmic desktopmonitor get screenheight, screenwidth` just strings the two values together, inputting them separately as:
```
wmic desktopmonitor get screenheight
wmic desktopmonitor get screenwidth
```
or however they're input in the script doesn't return any values either.

**Comment by darealshinji** [comment]
Should now work, as well as the GPU detection (didn't realize that wasn't working too).

**Comment by vinhphu56** [comment]
Hello,
I have a weird problem with this as well. I have a same Windows 7 setup on a VMWare and a physical PC, both are running Windows 7 32-bit. The difference is the physical PC is using the Microsoft Standard VGA. When I type the command the virtual machine, I get the resolution back but on the physical PC, I get nothing. Here is the command:
wmic desktopmonitor get screenheight, screenwidth
It looks like the problem is the Microsoft Standard VGA driver on the physical PC. Does anyone have this same problem?
