### ISSUE TITLE
Guake terminal

### ISSUE THREAD

**Issue by Isseq** [KittyKatt/screenFetch#355]
In Guake 0.8.4 cant't detect shell
screenFetch - Version 3.7.0
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)

![image](https://cloud.githubusercontent.com/assets/16752210/15401030/94ec52bc-1e0f-11e6-8395-4bfe8647ca8d.png)

**Comment by darealshinji** [comment]
Works without problems for me when I tested it in Ubuntu 16.04 VM.

**Comment by Isseq** [comment]
Yeah!
I turned off checkbox "Run command as a login shell" in guake properties
