### ISSUE TITLE
Simple Caching Script

### ISSUE THREAD

**Issue by cookrn** [KittyKatt/screenFetch#356]
I like seeing `screenfetch` display when I open new terminals, but the wait was noticeable when opening multiple new terminal tabs or GNU Screen windows. So, I wrote a simple little ruby script to cache the output.

https://gist.github.com/cookrn/885e45acb07f7cce51caaa70c34bab98

Here's the source:

```ruby
#!/usr/bin/env ruby

if fetched_file_blank? or fetched_file_expired?
  fetch!
end

write_cached_screenfetch!

BEGIN {
  COMMAND = 'screenfetch'.freeze
  EXPIRATION_TIMEOUT = 5 * 60 # 5 minutes
  FETCHED_PATH = File.expand_path('~/.screenfetched').freeze
  WRITE_MODE = 'w'.freeze

  def fetch!
    File.open(FETCHED_PATH, WRITE_MODE) do |f|
      if f.flock(File::LOCK_EX|File::LOCK_NB)
        f.write(`#{COMMAND}`)
        f.flush
      else
        f.flock(File::LOCK_EX)
      end

      f.flock(File::LOCK_UN)
    end
  end

  def fetched_file_blank?
    !File.exist?(FETCHED_PATH)
  end

  def fetched_file_expired?
    Time.now - File.mtime(FETCHED_PATH) > EXPIRATION_TIMEOUT
  end

  def write_cached_screenfetch!
    File.open(FETCHED_PATH) do |f|
      f.flock(File::LOCK_SH)
      puts(f.read)
    end
  end
}
```

I call the script `screenfetched` and place a call to it in my bash profile instead of `screenfetch` as I was using before. That way, when I open a bunch of new sessions at once either they're slow until the first one finishes, or they're all fast if it's already cached.

**Comment by cookrn** [comment]
Also, since this isn't really an issue, but more of a "heads up" 😄  anyone should feel free to close!

**Comment by cookrn** [comment]
Note, this does show `Shell: screenfetched` as the shell instead of something like `Shell: bash 3.2.57`

**Comment by DmitryHetman** [comment]
Good idea

**Comment by DmitryHetman** [comment]
Better to add it to the screenfetch and call from screenfetch if threre is no cached file.
cache you need to store in ~.cache/screenfetch
May be better rewrite this code to bash since ruby interpreter not installed by default on some systems;

**Comment by DmitryHetman** [comment]
Which lines exatly does it caches? 
You need add option to screenfetch to update cache.
hostname can be changed,
Kernel can be changed
Packages can be changed,
Shell can be changed

**Comment by cookrn** [comment]
Currently, this is just a wrapper script that will cache the output of `screenfetch` and use that if within the specified timeout. Feel free to rewrite in bash or python. Closing unless others would like discuss adding it into this codebase.
