### ISSUE TITLE
Solus logo changed!!

### ISSUE THREAD

**Issue by IronJaeger** [KittyKatt/screenFetch#358]
Hi,

I would like to inform you that after the rebranding of solus in the few last weeks, it now have an official definitive appropriate logo that you can see in their website www.solus-project.com and their social media accounts.
I tried to make an ascii version of it for help. I hope it's what needed http://pastebin.com/BfrjcSEV
thanks for the wanderful screenfetch :)

**Comment by tylcha** [comment]
This appears to be too many rows of text tall to be supported.

If it could be reworked to be around ~17 rows then it would most likely work.

I've tried playing with ascii art generators and the logo to get something that looks decent, but they all come out pretty goofy looking.
