### ISSUE TITLE
Support Bash on Windows 10

### ISSUE THREAD

**Issue by wbsdty331** [KittyKatt/screenFetch#360]
![qq 20160618010946](https://cloud.githubusercontent.com/assets/4280572/16158752/5a4d36c8-34f1-11e6-8c1d-747b581af497.png)

`Windows 10 Insider 14367`

**Comment by darealshinji** [comment]
Afaik it's actually a type of virtualized GNU/Linux system running inside Windows, so identifying it as Ubuntu is probably not _that_ wrong at all. I will definitely take a look at it when this feature is available in the stable release of Windows 10.
Also it seems the script is now working because someone else reported problems with it: https://github.com/KittyKatt/screenFetch/issues/339

**Comment by wbsdty331** [comment]
@darealshinji 
> Afaik it's actually a type of **virtualized** GNU/Linux system running inside Windows

if you have the interest,  You can read this Article: [Click Here](http://www.hanselman.com/blog/DevelopersCanRunBashShellAndUsermodeUbuntuLinuxBinariesOnWindows10.aspx)

> This isn't VM. This is a real native Bash Linux binary running on Windows itself. It's fast and lightweight and it's the real binaries. This is an genuine Ubuntu image on top of Windows with all the Linux tools I use like awk, sed, grep, vi, etc. It's fast and it's lightweight. The binaries are downloaded by you - using apt-get - just as on Linux, because it is Linux. You can apt-get and download other tools like Ruby, Redis, emacs, and on and on. 

**This runs on 64-bit Windows and doesn't use virtual machines,**

**Comment by darealshinji** [comment]
I've installed it and `uname`, `lsb_release` or files inside `/etc` don't seem to give any hints that it's running inside Windows.

**Comment by darealshinji** [comment]
What about this?

``` diff
--- a/screenfetch-dev
+++ b/screenfetch-dev
@@ -888,7 +888,14 @@
 		suse*linux*enterprise) distro="SUSE Linux Enterprise" ;;
 		tinycore|tinycore*linux) distro="TinyCore" ;;
 		trisquel) distro="Trisquel";;
-		ubuntu) distro="Ubuntu" ;;
+		ubuntu)
+			distro="Ubuntu"
+			if grep -q 'Microsoft' /proc/version 2>/dev/null || \
+			   grep -q 'Microsoft' /proc/sys/kernel/osrelease 2>/dev/null
+			then
+				uow=" (Ubuntu on Windows 10)"
+			fi
+			;;
 		viperr) distro="Viperr" ;;
 		void) distro="Void" ;;
 	esac
@@ -4618,7 +4625,7 @@
 				if [ -n "$distro_more" ]; then mydistro=$(echo -e "$labelcolor OS:$textcolor $distro_more")
 				else mydistro=$(echo -e "$labelcolor OS:$textcolor $distro $sysArch"); fi
 			fi
-			out_array=( "${out_array[@]}" "$mydistro" )
+			out_array=( "${out_array[@]}" "$mydistro$uow" )
 			((display_index++))
 		fi
 		if [[ "${display[@]}" =~ "kernel" ]]; then mykernel=$(echo -e "$labelcolor Kernel:$textcolor $kernel"); out_array=( "${out_array[@]}" "$mykernel" ); ((display_index++)); fi
```

![screen-2016-06-26_12-47-59](https://cloud.githubusercontent.com/assets/5700937/16361817/550d3c92-3b9c-11e6-9040-95e23acd6003.png)

**Comment by wbsdty331** [comment]
good,But I have a suggestion
This String (`Ubuntu on Windows 10`)  
I think it can be highlighted(such as Red or Blue)

That's it.
Thanks for your working :)

**Comment by darealshinji** [comment]
Added in commit https://github.com/KittyKatt/screenFetch/commit/d162f5befb8532e78c3c6b2a03bb3c2df1cff417
