### ISSUE TITLE
LXDE is not being detected

### ISSUE THREAD

**Issue by delirein** [KittyKatt/screenFetch#361]
Screenfetch version 3.6.8, running on Void Linux, reports
:: Finding desktop environment...found as 'Not Present'
while LXDE is being installed and running.

**Comment by darealshinji** [comment]
Latest release version is 3.7.0 and that works for me:
![virtualbox_void_27_06_2016_13_07_35](https://cloud.githubusercontent.com/assets/5700937/16377797/623c5e94-3c68-11e6-92a5-5ffe065c1ff4.png)
