### ISSUE TITLE
Detect Android correctly

### ISSUE THREAD

**Issue by Rudloff** [KittyKatt/screenFetch#362]
Hello,

There is now a screenfetch package for Termux. The only thing we add to patch was removing the comments on the Android detection code (https://github.com/termux/termux-packages/blob/master/packages/screenfetch/screenfetch-dev.patch).

I see in #86 that this method causes false positive. Maybe you could check for the `/system/build.prop` file instead? I think it only exists on Android.

**Comment by darealshinji** [comment]
Is `uname` available on Android? Or does it just say `GNU/Linux`?

**Comment by Rudloff** [comment]
uname is packaged in Termux and `uname -o` outputs `Android`. But it is not included in Android itself so I don't think it is a reliable way to detect Android.

**Comment by darealshinji** [comment]
I'm currently checking Android x86 and that one outputs `Linux` for `uname -o`. `/system/build.prop` seems to be an Android exclusive file so using that to distinct from other unices could be a reliable method.

**Comment by darealshinji** [comment]
Does this work as detection?
``` sh
# Check for android
if [[ "$(getprop >/dev/null 2>&1 | grep '\[ro\.board\.platform\]' | awk '{print $2}')" =~ "android" ]]; then
	distro="Android"
	detectmem
	detectuptime
	detectkernel
	detectdroid
	infoDisplay
	exit 0
fi
```
It does at least not interfere with detection on Ubuntu.

**Comment by Rudloff** [comment]
It does not seem to work. I added your code and I still get the Linux ASCII art.

**Comment by darealshinji** [comment]
So then just look for `/system/build.prop` considering it should really only be available on Android systems:
``` sh
if [ -f /system/build.prop ]; then
```

**Comment by Rudloff** [comment]
Yes, it works correctly.

**Comment by darealshinji** [comment]
Android checks enabled in https://github.com/KittyKatt/screenFetch/commit/ded651c99bc7c613ae90dd8b5c52842f18eef011
Closing this issue.
