### ISSUE TITLE
Add SparkyLinux logo

### ISSUE THREAD

**Issue by MilkyPL** [KittyKatt/screenFetch#365]
This Debian-based distro is very cool and getting more popular every day. I tried to add it and make a pull request but i'm a complete noob and it was throwing errors. 
![sparkylinux](https://cloud.githubusercontent.com/assets/20266576/16835862/fe40e8e6-49ba-11e6-949a-753496b83740.png)

**Comment by MilkyPL** [comment]
cat /etc/lsb-release
`DISTRIB_ID=Sparky
DISTRIB_RELEASE=4
DISTRIB_CODENAME=Tyche
DISTRIB_DESCRIPTION="SparkyLinux"
`
cat /etc/os-release
`PRETTY_NAME="SparkyLinux Tyche"
NAME="SparkyLinux"
ID=sparky
HOME_URL="http://sparkylinux.org/"
SUPPORT_URL="http://sparkylinux.org/forum/"
BUG_REPORT_URL="http://sourceforge.net/p/sparkylinux/tickets"
`

**Comment by darealshinji** [comment]
If it's Debian-based, what's the output of `cat /etc/debian_version`?

**Comment by MilkyPL** [comment]
`stretch/sid`

**Comment by DmitryHetman** [comment]
Why not use Debian unstable instead?

**Comment by darealshinji** [comment]
> Why not use Debian unstable instead?

A little off-topic, don't you think?

@MilkyPL 
I would have already added the logo, but man, it's not easy to make a good looking ASCII art from that fancy spiral.

**Comment by dylanaraps** [comment]
Here's what I came up with for the ascii, feel free to use it.

```sh
           .            `-:-`                  
          .o`       .-///-`                    
         `oo`    .:/++:.                       
         os+`  -/+++:` ``.........```          
        /ys+`./+++/-.-::::::----......``       
       `syyo`++o+--::::-::/+++/-``             
       -yyy+.+o+`:/:-:sdmmmmmmmmdy+-`          
::-`   :yyy/-oo.-+/`ymho++++++oyhdmdy/`        
`/yy+-`.syyo`+o..o--h..osyhhddhs+//osyy/`      
  -ydhs+-oyy/.+o.-: ` `  :/::+ydhy+```-os-     
   .sdddy::syo--/:.     `.:dy+-ohhho    ./:    
     :yddds/:+oo+//:-`- /+ +hy+.shhy:     ``   
      `:ydmmdysooooooo-.ss`/yss--oyyo          
        `./ossyyyyo+:-/oo:.osso- .oys          
       ``..-------::////.-oooo/   :so          
    `...----::::::::--.`/oooo:    .o:          
           ```````     ++o+:`     `:`          
                     ./+/-`        `           
                   `-:-.                       
                   ``                                                                 
```

**Comment by darealshinji** [comment]
@dylanaraps Thanks, I've added the logo.
