### ISSUE TITLE
Shell detection displays script call

### ISSUE THREAD

**Issue by GillesJ** [KittyKatt/screenFetch#366]
The filename of the shell script is displayed from which screenfetch is called.
e.g. an executable shell scipt with the name sfcallscript, called with "sh sfcallscript":

```
#!/bin/sh

echo
screenfetch
echo
```

Outputs "Shell: sh sfcallscript"

My particular use case for calling screenfetch in this manner is for "message of the day" (motd) functionality for servers where different users are running different shells.

**Comment by darealshinji** [comment]
You can try to export `$shell_type` before running screenfetch, like this:
``` sh
#! /usr/bin/env bash
export shell_type="$(basename "$(sed -e '1!d; s|#||; s|!||; s|/usr/bin/env||; s|^[ \t]*||' "$0")")"
screenfetch
```
It will convert the shebang of the called script into a single shell name. In this example sF wil output `Shell: bash 4.3.11` for me.

**Comment by GillesJ** [comment]
The issue is that that solution gets the currently installed bash version string. If you fsh, zsh or different is your active shell that won't be displayed.

I read up on shell detection and it seems far from trivial to implement. This is probably edge-case functionality so I will close this issue.
