### ISSUE TITLE
Gpu info  breaks the distro logo

### ISSUE THREAD

**Issue by kouros17** [KittyKatt/screenFetch#372]
Is there any way to shorten the info of gpu (or to change it) as not to be so much the length of the terminal?
If I shorten the length of the terminal then the displayed information about gpu breaks the manjaro-logo.
I tried `screenfetch -t` but doesn't work

![62e775a04a383f6b86aadebc5babaca7c84419d5](https://cloud.githubusercontent.com/assets/3219560/17465225/61e01d16-5cfa-11e6-9a3a-8ea0f3b48cf6.png)

![de430e1971253eb61c25e1d261ec6bac68c32c76](https://cloud.githubusercontent.com/assets/3219560/17465227/6cb7b578-5cfa-11e6-8106-bfbaafe72e25.png)

![b7285bb88ab3244d86afd77c8029383d62fdb66d](https://cloud.githubusercontent.com/assets/3219560/17465229/73958848-5cfa-11e6-8105-bb28f71a93d7.png)

Running **inxi -Gx** I get:
```
inxi -Gx
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Oland [Radeon HD 8570 / R7 240/340 OEM]
           bus-ID: 01:00.0
           Display Server: X.Org 1.17.4 driver: radeon
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD OLAND (DRM 2.45.0 / 4.7.0-0-MANJARO, LLVM 3.8.1)
           GLX Version: 3.0 Mesa 12.0.1 Direct Rendering: Yes
```

Is it  possible to display the info about graphics card (Advanced Micro Devices AMD/ATI Oland Radeon HD 8570 / R7 240/340 OEM) instead of GLX Renderer (Gallium 0.4 on AMD OLAND (DRM 2.45.0 / 4.7.0-0-MANJARO, LLVM 3.8.1)?

**Comment by DmitryHetman** [comment]
Install Gentoo

**Comment by DmitryHetman** [comment]
Also better use English language in menu. For input  and output in native language leave UTF-8 encoding in OS, but chose C or POSIX as main.

**Comment by darealshinji** [comment]
> Install Gentoo

The problems is not the choice of OS, the problem is that it's not displayed correctly.

> Is it possible to display the info about graphics card (Advanced Micro Devices AMD/ATI Oland Radeon HD 8570 / R7 240/340 OEM) instead of GLX Renderer (Gallium 0.4 on AMD OLAND (DRM 2.45.0 / 4.7.0-0-MANJARO, LLVM 3.8.1)?

Preferring the card info over the GLX renderer info sounds good. Though the displayed line will have about the same length.

**Comment by kouros17** [comment]
With propriety driver (catalyst) I get something like "AMD R7 200 series" with shorter length and everything is o.k.
Is there a way to change the displayed line?

**Comment by darealshinji** [comment]
The issue with breaking the logo should now be fixed.
@kouros17  If you still think it's a good idea to change the GPU detection I'd suggest you to open a new issue.

**Comment by kouros17** [comment]
I confirm that fixed!
Thanks a lot darealshinji!
