### ISSUE TITLE
Manjaro has a new logo

### ISSUE THREAD

**Issue by kainonergon** [KittyKatt/screenFetch#373]
Hi, Manjaro renewed its logo recently, now it has no gap on the left side.
https://github.com/manjaro/artworks/blob/master/logo/logo.png
![Manjaro logo](https://raw.githubusercontent.com/manjaro/artworks/master/logo/logo.png)

**Comment by oberon2007** [comment]
See https://github.com/KittyKatt/screenFetch/pull/420
