### ISSUE TITLE
screenfetch kills gnome-terminal

### ISSUE THREAD

**Issue by Lerentis** [KittyKatt/screenFetch#379]
if I run screenfetch -s it takes the screenshot normally, but after that i am not able to start gnome-terminal until I reboot my system.
Are there any logs I could provide to give more details about this issue?

Arch Linux
GNOME Version 3.20.2
screenfetch-git

```
systemctl --user --failed
  UNIT                          LOAD   ACTIVE SUB    DESCRIPTION
● gnome-terminal-server.service loaded failed failed GNOME Terminal Server

```

```
gnome-terminal --version
GNOME Terminal 3.20.2
```

```
gnome-terminal
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```

**Comment by DmitryHetman** [comment]
Xorg or Wayland?

**Comment by Lerentis** [comment]
Wayland. Here is my gdm custom.conf

```
cat /etc/gdm/custom.conf 
# GDM configuration storage

[daemon]
#WaylandEnable=false

[security]

[xdmcp]

[chooser]

[debug]
#Enable=true
```

**Comment by DmitryHetman** [comment]
Enable debug option and see what happens, post your log and output here.

**Comment by Lerentis** [comment]
even with this option enabled, no log is created.
/var/log/gdm is empty

I highly doubt that this issue has something to do with gdm thou.

**Comment by cicku** [comment]
Would you please paste your `/var/log/messages` to somewhere like pastebin?

**Comment by Lerentis** [comment]
I have no folder messages in /var/log/
```
[root@Muninn Code]# ls -al /var/log/
total 748
drwxr-xr-x  10 root root              4096  4. Sep 17:42 .
drwxr-xr-x  12 root root              4096  2. Mai 00:08 ..
-rw-------   1 root utmp                 0  1. Sep 12:47 btmp
-rw-------   1 root utmp                 0  1. Aug 00:00 btmp.1
drwxr-xr-x   2 root root              4096  4. Sep 13:14 cups
-rw-------   1 root root             32032  4. Sep 14:09 faillog
drwx--x--x   2 root gdm               4096 29. Jul 19:00 gdm
drwxr-xr-x   2 root root              4096 31. Mär 2015  gssproxy
-rw-r--r--   1 root root               307 17. Aug 23:33 gufw.log
drwxr-sr-x+  4 root systemd-journal   4096  2. Mai 00:08 journal
-rw-r--r--   1 root root            292292  4. Sep 13:33 lastlog
drwx--x--x   2 root lightdm           4096 12. Mai 21:33 lightdm
drwxr-xr-x   2 root root              4096 30. Sep 2015  old
-rw-r--r--   1 root root            339524  4. Sep 17:14 pacman.log
-rw-r--r--   1 root root             36889 11. Aug 14:49 pamac.log
drwxr-xr-x   2 root root              4096  8. Jul 22:55 samba
drwxr-xr-x   2 root root              4096 19. Sep 2015  speech-dispatcher
-rw-rw-r--   1 root utmp            212736  4. Sep 14:09 wtmp
-rw-r--r--   1 root root             16664 12. Mai 22:50 Xorg.0.log
-rw-r--r--   1 root root             16664 12. Mai 22:47 Xorg.0.log.old
-rw-r--r--   1 root root               599 12. Mai 22:50 Xorg.1.log
-rw-r--r--   1 root users            41219 12. Mai 22:41 Xorg.1.log.old
```
and gdm is empty:
```
[root@Muninn Code]# ls -al /var/log/gdm/
total 8
drwx--x--x  2 root gdm  4096 29. Jul 19:00 .
drwxr-xr-x 10 root root 4096  4. Sep 17:42 ..
```

**Comment by cicku** [comment]
Try `journalctl -b | grep gnome`

**Comment by Lerentis** [comment]
here is a pastebin of that output (beginning with the error)

http://pastebin.com/mWvG7PpQ

also it stated that there is a "non UTF-8 locale" but I don't have it set anywhere i know of.

```
[lerentis@Muninn ~]$ localectl status
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_DE.UTF-8
                  LC_TIME=de_DE.UTF-8
                  LC_MONETARY=de_DE.UTF-8
                  LC_PAPER=de_DE.UTF-8
                  LC_MEASUREMENT=de_DE.UTF-8
       VC Keymap: de
      X11 Layout: de
```

**Comment by cicku** [comment]
```
Sep 04 19:00:59 Muninn dbus-daemon[2535]: Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service'
Sep 04 19:00:59 Muninn gnome-terminal-server[25744]: Non UTF-8 locale (ANSI_X3.4-1968) is not supported!
Sep 04 19:00:59 Muninn systemd[2503]: gnome-terminal-server.service: Main process exited, code=exited, status=8/n/a
Sep 04 19:00:59 Muninn systemd[2503]: gnome-terminal-server.service: Unit entered failed state.
Sep 04 19:00:59 Muninn systemd[2503]: gnome-terminal-server.service: Failed with result 'exit-code'.
```

Hazard a guess, it should be a locale problem, as I'm seeing similar reports on different OS. Here are some helpful links for Arch, you can give it a try:

https://bbs.archlinux.org/viewtopic.php?id=180103
https://bbs.archlinux.org/viewtopic.php?id=212638

**Comment by Lerentis** [comment]
both links you suggested deal with a completely not working gnome-terminal. in my case gnome-terminal works fine until i use screenfetch -s.
also i just checked again. i only have utf8 locales set. do you know another way to set them apart from:

```
localectl set-locale LANG="en_US.UTF-8"
/etc/locale.conf
/etc/vconsole.conf
```

I also tried to reinstall gdm, and remove all gdm libs as suggested by another thread (which i somehow cant find anymore ._.)

**Comment by Lemmmy** [comment]
not sure if its related, but often on my system i have problems with gnome-terminal never starting until i reboot. i am able to fix them with this command: `systemctl --user import-environment DISPLAY XAUTHORITY`

**Comment by Lerentis** [comment]
sadly not working for this issue :/

**Comment by ilovesusu** [comment]
我也是这个问题,我的是LANG="zh_cn.UTF-8"

**Comment by kouros17** [comment]
Found another work around. Edit **/usr/bin/screenfetch** to comment out the following lines:
```
LANG=C
LANGUAGE=C
LC_ALL=C
```
to:
```
#LANG=C
#LANGUAGE=C
#LC_ALL=C
```

**Comment by Lerentis** [comment]
If i comment out these 3 lines it kind of works, but my profile is gone after that (color, size etc.). at least i can open the terminal after :D
Thank you @kouros17 
the second one does not have any effect on my machine

**Comment by cicku** [comment]
Still prove to be a locale problem.

**Comment by Lerentis** [comment]
@cicku might be, but what i can tell from [this](https://bbs.archlinux.org/viewtopic.php?id=215059) post and the corresponding [bugreport](https://bugs.archlinux.org/task/50106) it might be more a problem with overwriting LANG/LANGUAGE and LC_ALL, which are all set normally on my system, but get messed up after running screenfetch.

**Comment by solbjorn** [comment]
It's not a screenfetch bug, it comes from gnome-session 3.20.2+. Arch users may try to build latest gnome-session with patch from this post: https://bugs.archlinux.org/task/50069#comment152232
I did it myself and it fixed locale problems on my OS.

**Comment by darealshinji** [comment]
Closing, as it apparently isn't a screenFetch bug.

**Comment by kouros17** [comment]
Thank you @solbjorn, this solved the problem for me too!
