### ISSUE TITLE
Add CPU Temperature.

### ISSUE THREAD

**Issue by DmitryHetman** [KittyKatt/screenFetch#381]
Use 
cat /sys/devices/virtual/thermal/thermal_zoneN/temp
where N is a 1or 0 (not sure where is cpu and where chipset)
for detecting CPU temperature.

**Comment by darealshinji** [comment]
I get 29800 and 35000. Is that 29.8 and 35 °C?

**Comment by tobbez** [comment]
Yes. According to Linux' `Documentation/thermal/sysfs-api.txt`:
```
 temp
 	Current temperature as reported by thermal zone (sensor).
 	Unit: millidegree Celsius
 	RO, Required
```

See also /sys/class/hwmon/ (covered by `Documentation/hwmon/sysfs-interface` in the Linux sources) for other sensors.

Alternatively, use lm_sensors (if/when available).

**Comment by darealshinji** [comment]
https://github.com/KittyKatt/screenFetch/commit/a1cacfc90d09dfb82c0f2f9275de7bc50b000cf3

**Comment by darealshinji** [comment]
I'm closing this, since the feature was added.
