### ISSUE TITLE
Does not detect KDE neon Plasma 5.7.5 Developer Edition

### ISSUE THREAD

**Issue by cuteredpwnda** [KittyKatt/screenFetch#382]
So I got this issue where screenfetch does not detect my Distro correctly.
I've seen an ASCII Logo for KDE Neon posted and commited here too.

And in addition: I am too stupid to let screenfetch run when I open my terminal.

Thanks in advance
cuteredpwnda

**Comment by darealshinji** [comment]
What's your output of `lsb_release -sirc`, `cat /etc/issue` and `cat /etc/os-release`? Do recent versions of KDE Neon have unique files inside `/etc`, maybe something like `/etc/neon-release`?

To start sF every time you open a terminal, you must add the command to run the script at the bottom of `$HOME/.bashrc` (if you're using bash).

**Comment by darealshinji** [comment]
No problems here with 5.7.5 user edition and 5.8.90 developer edition.
