### ISSUE TITLE
error on line 4156, 4157 in FreeBSD 11.0

### ISSUE THREAD

**Issue by r2qokk** [KittyKatt/screenFetch#396]
version ```3.6.8```
line 4156 => ```/dev/fd/62: Operartion not supported```
line 4157 => ```3: Bad file descriptor```
```uname -a``` => ```FreeBSD 11.0-RELEASE-p1```
```bash --version``` => ```4.4.0(0)-release```

The picture is showed as UNIX with no OS information on the side.
Reproducible when installing from both ```pkg``` and ```ports```

It is good when mark out line 4156-4158, and replace line 4157 with ```detect${i} 2```

**Comment by darealshinji** [comment]
Can you open a pull request with your fix?
