### ISSUE TITLE
Omitting host var causes next line to indent

### ISSUE THREAD

**Issue by polyzen** [KittyKatt/screenFetch#401]
![Screenshot](https://ptpb.pw/dN_F.png)

Version: 3.7.0
Host: Arch Linux
Terminal: termite

**Comment by darealshinji** [comment]
![spectacle vr9145](https://cloud.githubusercontent.com/assets/5700937/20242697/76fa2c84-a938-11e6-85d6-0ca0c8e2baa0.png)
No issue here...

**Comment by polyzen** [comment]
Installed the devel version; apparently it's already been fixed.

Apologies, and thank you!
