### ISSUE TITLE
KDE4 - fonts are not detected right (it detecting current gtk font)

### ISSUE THREAD

**Issue by actionless** [KittyKatt/screenFetch#41]
subj

**Comment by KittyKatt** [comment]
@actionless I don't even know if you still use screenfetch, but could you try using latest master again and report back it this issue still exists? Thank you for reporting.

**Comment by actionless** [comment]
i can install screenfetch any time to test, however i couldn't install kde4 so easily, unfortunately

also since kde4 is not actual anymore, i suggest closing this

unless someone else will be able to reproduce it under kde5
