### ISSUE TITLE
GPU AMD RX 480 is not showing properly

### ISSUE THREAD

**Issue by GregoryIstratov** [KittyKatt/screenFetch#413]
![scrfetc](https://cloud.githubusercontent.com/assets/11486152/20248032/45b72c9a-a9f5-11e6-9144-58d6a39555bc.png)

**Comment by darealshinji** [comment]
Maybe I have to revert commit https://github.com/KittyKatt/screenFetch/commit/0f516ae237a521b7e25a20b6f352dd7e60571591

**Comment by GregoryIstratov** [comment]
Yeah, glxinfo shows right result : OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics
