### ISSUE TITLE
Freebsd problem

### ISSUE THREAD

**Issue by oscarandrea** [KittyKatt/screenFetch#416]
use freebsd 11, I installed screenfetch through ports, unfortunately freebsd is not detected and appears ascii "unix", these are the error strings

`$ screenfetch
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
/usr/local/bin/screenfetch: line 4156: /dev/fd/62: Operation not supported
/usr/local/bin/screenfetch: line 4157: 3: Bad file descriptor
`

**Comment by darealshinji** [comment]
Afaik bash requires fdescfs(5) and procfs(5) to be mounted to work correctly.

**Comment by oscarandrea** [comment]
thanks, solved
`
  mount -t fdescfs fdesc /dev/fd
  mount -t procfs proc /proc
`
