### ISSUE TITLE
xprop: error: Invalid window id format: _NET_SUPPORTING_WM_CHECK.

### ISSUE THREAD

**Issue by Fuuzetsu** [KittyKatt/screenFetch#42]
Don't you just love xprop errors?

![lovelyxprop](https://f.cloud.github.com/assets/893115/209189/27eff60e-825f-11e2-9cea-82eb39ad3eb7.png)

**Comment by KittyKatt** [comment]
I'm going to mark this as WONTFIX at this point. Closing.
