### ISSUE TITLE
Add support for SwagArch GNU/Linux

### ISSUE THREAD

**Issue by memoryleakx** [KittyKatt/screenFetch#421]
#126
Web: https://swagarch.github.io
Logo: [SwagArch GNU/Linux](https://raw.githubusercontent.com/SwagArch/swagarch-build/master/airootfs/usr/share/pixmaps/swagarch-logo.svg)

cat /etc/os-release
NAME="SwagArch"
ID=swagarch
PRETTY_NAME="SwagArch"
ANSI_COLOR="0;35"
HOME_URL="https://swagarch.github.io"
SUPPORT_URL="https://plus.google.com/u/0/communities/112748817922552005139"
BUG_REPORT_URL="https://github.com/SwagArch/swagarch-build/issues"

**Comment by darealshinji** [comment]
Does it identify itself through `lsb_release -sirc`?

**Comment by darealshinji** [comment]
Detection and logo added.

![logo](https://cloud.githubusercontent.com/assets/5700937/20858539/010a084a-b947-11e6-9b24-c06a2e40d72f.png)

**Comment by memoryleakx** [comment]
@darealshinji Thank you 👍
