### ISSUE TITLE
Add support for GuixSD

### ISSUE THREAD

**Issue by baconicsynergy** [KittyKatt/screenFetch#429]

**Comment by darealshinji** [comment]
A bit more information would be appreciated.

**Comment by DmitryHetman** [comment]
Liberating. GuixSD is an advanced distribution of the GNU operating system developed by the GNU Project —which respects the freedom of computer users.
Dependable. The GNU Guix package manager, in addition to standard package management features, supports transactional upgrades and roll-backs, unprivileged package management, per-user profiles, and more.
Hackable. It provides Guile Scheme APIs, including high-level embedded domain-specific languages (EDSLs) to define packages and whole-system configurations.

**Comment by DmitryHetman** [comment]
if OS have guix package manager then it GuixSD, or you can just read /etc/os-release if it has one.

**Comment by darealshinji** [comment]
Can someone provide a VirtualBox image? I'm not able to install it in VBox.

**Comment by mohamed-aziz** [comment]
@darealshinji you can do a
➔ xz -dv guixsd-usb-install-0.12.0.i686-linux.xz
to uncompress the file and
➔ vboxmanage convertfromraw guixsd-usb-install-0.12.0.i686-linux guix.vdi --format vdi
to make the vdi file and then just mount it as a disk.

**Comment by konfou** [comment]
I think this can be closed now.
