### ISSUE TITLE
Fix Readme.md (Fedora installation instructions)

### ISSUE THREAD

**Issue by X3MBoy** [KittyKatt/screenFetch#432]
Fedora doesn't use yum anymore. Right command should be `dnf install screenfetch`

**Comment by darealshinji** [comment]
From which version on?

**Comment by X3MBoy** [comment]
Officially, since Fedora 22, dnf is the default package manager in Fedora [1]. Even when yum command make a redirection to dnf:

`Redirecting to '/usr/bin/dnf install package' (see 'man yum2dnf')`

It's not right to still make people to use deprecated packages.

[1] https://fedoraproject.org/wiki/DNF

**Comment by darealshinji** [comment]
I've updated the readme file.
