### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by cstrouse** [KittyKatt/screenFetch#436]
It's been quite a long time since a release has been made. I'm adding a package to [chromebrew](https://github.com/skycocker/chromebrew). Adding a current version using a tagged release would be preferable over pulling from git.

**Comment by darealshinji** [comment]
You should try to contact KittyKatt and ask him to make a new release. I would do it, but I don't know how he does the version numbering.

**Comment by candrews** [comment]
@KittyKatt it sounds like if let @darealshinji know what the release number should be (the last release was 3.7.0), he can take care of the rest. What do you say?

**Comment by cstrouse** [comment]
@darealshinji the versioning seem pretty random to me. It would probably be a good idea to write up a changelog with the key work done since 3.7.0 and then use that to decide the best way to bump the version. I'd venture a guess that since it's been quite a while that 3.8.0 would be a good choice.

**Comment by KittyKatt** [comment]
You can go ahead and release 3.8 for now. The versioning wasn't done by any
specific scheme, just how much I thought it changed. Sorry for absence.
Life has been not so great.

**Comment by cstrouse** [comment]
Sorry to hear that @KittyKatt hopefully things will turn around for you soon. Thanks for helping with this.

**Comment by darealshinji** [comment]
A new release was published.
