### ISSUE TITLE
CPU temp could not be fetched in msys2

### ISSUE THREAD

**Issue by fhoshino** [KittyKatt/screenFetch#437]
Seems it will not be supported unless installing probes, should be hidden if probes not installed.
![conemu64_2017-02-03_23-33-05](https://cloud.githubusercontent.com/assets/771955/22597088/23430f08-ea69-11e6-9659-0245f0b1af82.png)

**Comment by DmitryHetman** [comment]
Install Gentoo

**Comment by darealshinji** [comment]
> DmitryHetman
Don't just post such off-topic things. sF is OS-independent, the more OSes it's been tested on and the more it supports, the better.

**Comment by MattSturgeon** [comment]
This was fixed by #532 however still affects the latest release version.

For now you can use the [dev script](https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev) here on github and ask @darealshinji nicely to make an new release ;)

**Comment by darealshinji** [comment]
Closing, since it's fixed.
