### ISSUE TITLE
SailfishOS not working

### ISSUE THREAD

**Issue by ghost** [KittyKatt/screenFetch#438]
Android is detected on SailfishOS because SailfishOS have /system/build.prop too.

**Comment by darealshinji** [comment]
Changing [this](https://github.com/KittyKatt/screenFetch/blob/fc16688e6d57eb666bb10aae014a9632c66bf839/screenfetch-dev#L5292) line to `if [ -f /system/build.prop ] && [ ${distro} != "SailfishOS" ]; then` may help.

**Comment by MisterMagisterDev** [comment]
With that change i'm getting:
./screenfetch-dev: line 5292: [: !=: unary operator expected
sorry i don't know python so i can only test :/

**Comment by darealshinji** [comment]
What's your output of `screenfetch -v`?

**Comment by DmitryHetman** [comment]
write "${distro}" instead of ${distro}

**Comment by darealshinji** [comment]
Does commit https://github.com/KittyKatt/screenFetch/commit/2172669ede838eb492847290f429ba1b0557f48d fix it?

**Comment by MisterMagisterDev** [comment]
Nope it's still detected as android.

**Comment by DmitryHetman** [comment]
Is it true that in SailFish OS everything works in VM?

**Comment by MisterMagisterDev** [comment]
Nope it's not true, it's not android

**Comment by DmitryHetman** [comment]
Cool

**Comment by Bx16** [comment]
Hi, still don't work for Sailfish :(
` nemo@Sailfish  ~  ./screenfetch-dev                          ✔  28  21:42:10
       ╲ ▁▂▂▂▁ ╱        
       ▄███████▄        
      ▄██ ███ ██▄        
     ▄███████████▄       OS: Android 7.1.2
  ▄█ ▄▄▄▄▄▄▄▄▄▄▄▄▄ █▄    Device: Redmi 5 Plus (vince)
  ██ █████████████ ██    ROM: vince-userdebug 7.1.2 NJH47F 9c646b9bbd test-keys
  ██ █████████████ ██    Baseband: msm
  ██ █████████████ ██    Kernel: aarch64 Linux 3.18.31-g7b90ce6
  ██ █████████████ ██    Uptime: 1d 11h 30m
     █████████████       CPU: Qualcomm Technologies, Inc MSM8953
      ███████████        GPU: Qualcomm Technologies, Inc MSM8953
       ██     ██         RAM: 2628MiB / 3474MiB
`

**Comment by Michal-Szczepaniak** [comment]
@darealshinji that doesn't work because lsb_release doesn't exist on sfos so therefore it never goes to Mer/SailfishOS if. we need standalone if to detect sfos

**Comment by Michal-Szczepaniak** [comment]
btw i fixed it in #621 PR

**Comment by darealshinji** [comment]
Merged it.
