### ISSUE TITLE
Update to README regarding Ubuntu Installing.

### ISSUE THREAD

**Issue by MichaelTunnell** [KittyKatt/screenFetch#439]
I didn't think this deserved a commit record of such a small change so that's why I am submitting an issue instead.

> 1. Ubuntu 16.04+: sudo apt install screenfetch
> 2. 14.04 or Debian: sudo apt-get install screenfetch

the apt install command was actually introduced in Ubuntu with version 14.04 so . . . 

`sudo apt install screenfetch`

works in all Ubuntu versions 14.04+

**Comment by darealshinji** [comment]
From what I understand `apt` is the recommended command on Ubuntu 16.04 or later, even if it was added in earlier versions (and it's probably available in Debian too), see commit https://github.com/KittyKatt/screenFetch/commit/cd66aa68f9f1bb1d463c86baaffa8138d03bc6a4

**Comment by mudongliang** [comment]
I think this `apt` command or tool is firstly introduced into Debian, and then Ubuntu. Maybe you need to place Debian into the 1st item, other than the 2nd item

**Comment by DmitryHetman** [comment]
apt is a default tool on debian-based systems

**Comment by darealshinji** [comment]
What about changing it like this?

### Ubuntu (14.04 or later) and Debian (stable/testing/unstable)

1. `sudo apt install screenfetch` or `sudo apt-get install screenfetch`
3. There is also a PPA for Ubuntu located at https://launchpad.net/%7Edjcj/+archive/ubuntu/screenfetch

**Comment by darealshinji** [comment]
I've updated the instructions.
