### ISSUE TITLE
Convert to ascii encoding.

### ISSUE THREAD

**Issue by DmitryHetman** [KittyKatt/screenFetch#444]

**Comment by darealshinji** [comment]
A bit more details please. Convert the sF script I assume? And why ASCII? You're having any layout issues?

**Comment by DmitryHetman** [comment]
There is UTF-8 redundant characters. Try iconv -f utf-8 -t us-ascii screenfetch-dev, it's better not use utf-8.

**Comment by DmitryHetman** [comment]
Accept my pull-request please.

**Comment by DmitryHetman** [comment]
cpu="$cpu [${temp}_C]" Contains UTF-8 character, easy to fix.
Logos which contains utf-8:
Alpine linux, CrunchBang, Fux, Mageia

**Comment by Darksider3** [comment]
Yeah, but i think the question ist "where ist the problem with UTF-8?".

**Comment by DmitryHetman** [comment]
On almost all GNU/Linux distros, glibc by default don't supports utf-8 as musl or uclibc.
And also many people just don't need it in system, so why use utf-8 characters whet it is unnecessary?

**Comment by DmitryHetman** [comment]
I wondering why this issue takes attention, but my previous request still empty, also pull-request not merged.

**Comment by Darksider3** [comment]
Musl, by default, supports UTF-8[1], and Glibc does support it [as well, as it seems.](http://www.gnu.org/software/libc/manual/html_node/Extended-Char-Intro.html)

uclibc, didn't even know about it, seems too support it, as you can see in their [FAQ](https://www.uclibc.org/FAQ.html)

Again, where is the problem? sF is a *bashscript*, that probably won't even care about the Libc-Port it is actually running on, if bash works on it.
[1] http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc

**Comment by darealshinji** [comment]
I don't see any benefit from converting the script to pure ASCII. And I don't think anyone has ever reported any issues. So I'm closing this issue.
