### ISSUE TITLE
No ParrotSec OS

### ISSUE THREAD

**Issue by 5P4D3** [KittyKatt/screenFetch#446]
Put a ParrotSec OS please

**Comment by darealshinji** [comment]
"Parrot Security" is among the supported distros. Does the detection not work?

**Comment by 5P4D3** [comment]
yes the logo is the penguin which is the linux.. :(
![screenshot at 2017-03-08 21-09-13](https://cloud.githubusercontent.com/assets/18681023/23705326/3ce81f30-0444-11e7-82ce-990c2346bbb4.png)

**Comment by darealshinji** [comment]
What's the output of `screenfetch -v`?

**Comment by 5P4D3** [comment]
![screenfetch](https://cloud.githubusercontent.com/assets/18681023/23784696/69975db0-059e-11e7-94ba-ab3e9857331f.png)

**Comment by darealshinji** [comment]
It says "distro found as parrot 3.5", weird. What's your output of `lsb_release -sirc`?
Does it help if you change the line
```
parrot|parrot*security) distro="Parrot Security" ;;
```
in the script to
```
parrot*) distro="Parrot Security" ;;
```
?

**Comment by 5P4D3** [comment]
lsb_release -sirc out put is
Parrot
3.5
CyberGalleon

which is the update version of Parrot Sec..

and where can i find that script you're talking about :)

**Comment by darealshinji** [comment]
I meant `screenfetch-dev`of course.

**Comment by 5P4D3** [comment]
i cant find that file here.. :(
i install screenfetch via command line..

**Comment by darealshinji** [comment]
https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev

**Comment by 5P4D3** [comment]
should i reisntall it and download this code on git?

**Comment by darealshinji** [comment]
Are you using screenFetch v3.8.0?

**Comment by 5P4D3** [comment]
i guess i know what's wrong.... im using an outdated version. :( how do i update it on terminal ?
![screenfetch](https://cloud.githubusercontent.com/assets/18681023/23935244/d39cb0d0-0985-11e7-9c2a-a5bb90d48f80.png)

**Comment by darealshinji** [comment]
ParrotSec uses Debian packages, right? You could manually download a package from my [PPA](https://launchpad.net/%7Edjcj/+archive/ubuntu/screenfetch) and install it. Or you download the script from Github and install it into `/usr/local/bin` or `$HOME/bin` (if the latter one is among your `PATH`).
