### ISSUE TITLE
bc: command not found

### ISSUE THREAD

**Issue by 5P4D3** [KittyKatt/screenFetch#450]
Why am i getting this error ? i successfully install the latest. however, it comes up with an error.
![command not found](https://cloud.githubusercontent.com/assets/18681023/23978693/622761e2-0a30-11e7-950d-68ffe9a78cce.png)

**Comment by darealshinji** [comment]
Have you installed bc? `sudo apt install bc`

**Comment by 5P4D3** [comment]
okay w8 ill try to install

**Comment by 5P4D3** [comment]
after installing bc .. No Errors and i edit my .bashrc :D thanks!
![d](https://cloud.githubusercontent.com/assets/18681023/23994836/a3cc4346-0a81-11e7-8cb1-e9afe68de686.png)
