### ISSUE TITLE
No GPU

### ISSUE THREAD

**Issue by sniper570** [KittyKatt/screenFetch#461]
awk: fatal: cannot open file `/proc/fb' for reading (No such file or directory)

**Comment by darealshinji** [comment]
Your OS?

**Comment by sniper570** [comment]
OS: CentOS on a remote connection via SSH

![screenshot from 2017-04-04 02-42-17](https://cloud.githubusercontent.com/assets/13314266/24634805/de2e6e02-18e0-11e7-87ba-356690413c08.png)

GPU line and error line should be suppressed if no framebuffer exists ;)

**Comment by DmitryHetman** [comment]
![170419rmrqonvjyspt](https://cloud.githubusercontent.com/assets/18743742/25191156/44de1686-251e-11e7-9b97-ad0483823ffc.png)
