### ISSUE TITLE
awk: fatal: cannot open file `/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq' for reading (Permission denied)

### ISSUE THREAD

**Issue by gschaffner** [KittyKatt/screenFetch#467]
Getting this error running Bash on Ubuntu on Windows. The rest of the printout seems to work properly still.

Issue #148 is similar, but unrelated I believe.

Thanks for your time.

**Comment by jpmck** [comment]
I'm getting the same error:

```[[ ! ]] awk: fatal: cannot open file `/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq' for reading (Permission denied)```

It looks like root owns the file...

```-rw-rw---- 1 root root 0 Jun  1 15:26 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq```

Running ```sudo screenfetch``` doesn't produce the error.

**Comment by lizy14** [comment]
quick fix:
```
sudo chmod 0664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
```

BTW, I believe this should be closed, as it is not an issue of screenfetch.
