### ISSUE TITLE
FreeBSD (10.0+) command pkg_info not found.

### ISSUE THREAD

**Issue by vesparv11** [KittyKatt/screenFetch#481]
After typing screenfetch in shell there is:
/usr/local/bin/screenfetch: line 887: pkg_info: command not found
and number of current packages is 0.

Solution:
In FreeBSD 10 there is no command pkg_info. It is replaced by command pkg info.

**Comment by darealshinji** [comment]
Any suggestion how to handle this without breaking older releases?

**Comment by DmitryHetman** [comment]
@darealshinji brake older releases.

**Comment by darealshinji** [comment]
Oldest supported release is 10.3, right? So I guess breaking old versions is fine. Will a simple replacement of `pkg_info` with `pkg info` fix it?
@vesparv11 Maybe you should make a PR, since you have FreeBSD installed to test if things work.

**Comment by DmitryHetman** [comment]
@darealshinji I guess so, but I'm not bsd guy. Someone should test it.

**Comment by vesparv11** [comment]
@DmitryHetman @darealshinji I can test it, just tell me how I should perform test. (never helped with bug fixing before)

**Comment by vesparv11** [comment]
![fix](https://cloud.githubusercontent.com/assets/19633124/26036272/a524d14a-38da-11e7-90a6-3c863801e518.jpg)

FIXED!
Replaced pkg_info to pkg info on line 1130. Everything is working correctly now :)

**Comment by darealshinji** [comment]
Lines 1127-1130 on the current script:
``` sh
		'FreeBSD')
			pkgs=$(if TMPDIR=/dev/null ASSUME_ALWAYS_YES=1 PACKAGESITE=file:///nonexistent pkg info pkg >/dev/null 2>&1; then
				pkg info | wc -l | awk '{print $1}'; else pkg_info | wc -l | awk '{sub(" ", "");print $1}'; fi)
		;;
```

Please make a suggestion on what to change here exactly, as the check used here to decide whether to use `pkg_info` or `pkg info` seems not to work from what I understand nor is it needed anymore.

**Comment by darealshinji** [comment]
So basically I can change the whole thing to this?
``` sh
'FreeBSD')
        pkgs=$(pkg info | wc -l | awk '{sub(" ", ""); print $1}';)
;;
```

**Comment by vesparv11** [comment]
![fix](https://cloud.githubusercontent.com/assets/19633124/26037224/52236762-38ef-11e7-8752-e0083d544ed8.jpg)

Yeah, it's working fine now.
