### ISSUE TITLE
Update the Ubuntu logo

### ISSUE THREAD

**Issue by dustinkirkland** [KittyKatt/screenFetch#484]
Ubuntu moved away from the 3-color "circle of friends" logo in 2009.  Could you please update to the modern Ubuntu logo?  See attached.  Thanks!

![ubuntu](https://cloud.githubusercontent.com/assets/838790/25852895/e305cb7c-3498-11e7-85b9-2d227c29adde.png)

**Comment by DmitryHetman** [comment]
What? Ubuntu died 1 month ago, please stop this.

**Comment by darealshinji** [comment]
What about ignoring the circle and just make the logo red (with a few more modifications)?

![ubuntu](https://cloud.githubusercontent.com/assets/5700937/26027250/10a60a90-380b-11e7-8181-cef1537ebde3.png)

**Comment by dustinkirkland** [comment]
+1, that works.  Thanks!

**Comment by darealshinji** [comment]
Logo was updated.
