### ISSUE TITLE
Add info for Zorin OS

### ISSUE THREAD

**Issue by thomasstevenson** [KittyKatt/screenFetch#486]
Pretty surprising that screenfetch doesn't already have any info for Zorin OS, one of the top 10 Linux distros on Distrowatch. You can take a look at netofetch for this, which has had support for Zorin OS for a while now.

**Comment by DmitryHetman** [comment]
Software description: zorin OS is an Ubuntu-based operating system aimed at Windows users that are switching over to Linux.
It's shit by definiton.

**Comment by darealshinji** [comment]
You don't want people to switch from Windows to Linux?

**Comment by DmitryHetman** [comment]
@darealshinji I want people to switch to real, good quality distros like Debian, Fedora - they as easy to install and use, even more - they have better and bigger community always ready to help.
zorin os is fork of ubuntu which is fork of debian.

**Comment by darealshinji** [comment]
A little more on topic: does Zorin identify itself as a separate distribution or will `lsb_release` identify it as `Ubuntu`?

**Comment by thomasstevenson** [comment]
@darealshinji Running `lsb_release -a` gives me this output:
```
Distributor ID:	Zorin
Description:	Zorin OS 12.1
Release:	12
Codename:	xenial
```

@DmitryHetman I'd recommend you to give the newest version of Zorin OS a shot, it's gotten really good (personally I think it's higher quality than even Ubuntu or Mint 18). Apparently Zorin OS has been around since 2009 and their newest version (which was released back in November) already got more than half a million downloads (http://zoringroup.com/blog/2017/03/21/zorin-os-12-hits-half-a-million-downloads/) so I don't think it should be dismissed.

**Comment by konfou** [comment]
`lsb_release -sirc`  returns `Zorin 12.1 xenial`?

**Comment by thomasstevenson** [comment]
@konfou Yes, but with `12` instead of `12.1`, as follows:
```
Zorin
12
xenial
```
