### ISSUE TITLE
Output not normal

### ISSUE THREAD

**Issue by XuanStar** [KittyKatt/screenFetch#488]
![screenshot_2017-05-21-19-49-50-256_com sonelli juicessh](https://cloud.githubusercontent.com/assets/22031498/26283807/37eac0a8-3e61-11e7-807f-3b89136538ed.png)

![screenshot_2017-05-21-19-50-01-979_com sonelli juicessh](https://cloud.githubusercontent.com/assets/22031498/26283680/2fc6f902-3e5f-11e7-81d2-2b2342be8fc5.png)

**Comment by liwakura** [comment]
Your font seems to have non-monospace block symbols, which are too wide. Can you try with an different font?

**Comment by konfou** [comment]
The only problem I see is Android logo not appearing as it should. The reason was given by @liwakura. If you want to print Apple's logo then you're giving the wrong command. It can be done as `screenfetch -A 'Mac OS X'`.
