### ISSUE TITLE
Redundant "Icon theme xxx not found" info - how to get rid of it?

### ISSUE THREAD

**Issue by michaldybczak** [KittyKatt/screenFetch#497]
I used in the past elementary icons. I don't anymore and they're no longer on my computer but screenfetch shows at the begining "Icon theme "elementary" not found.

How can I fix it?

**Comment by darealshinji** [comment]
What's the output of `screenfetch -v`?

**Comment by michaldybczak** [comment]
:: Finding distro...found as 'Manjaro 17.0.2'
:: Finding hostname and user...found as 'xxxxxx@xxx-PC'
:: Finding kernel version...found as 'x86_64 Linux 4.11.8-1-MANJARO'
:: Finding current uptime...found as '1h 22m'
:: Finding current package count...found as '1806'
:: Finding current shell...found as 'bash'
:: Finding current resolution(s)...found as '1920x1080'
Icon theme "elementary" not found.
:: Finding desktop environment...found as 'KDE 5.35.0 / Plasma 5.10.3'
:: Finding window manager...found as 'KWin'
:: Finding window manager theme...found as 'Breeze'
:: Finding GTK2 theme...found as 'macOS-Sierra-master'
:: Finding GTK3 theme...found as 'macOS-Sierra-master'
:: Finding icon theme...found as 'la-capitaine-icon-theme'
:: Finding user font...found as 'Noto Sans Regular'
:: Finding current CPU...found as 'Intel Core i7-6700HQ @ 8x 3.5GHz [55.5°C]'
:: Finding current GPU...found as 'Not Found'
:: Finding current RAM usage...found as '2269MiB / 7855MiB'

The laptop has hybrid GPU-based on bumblebee, maybe that is why it was unable to find it, but still, Intel GPU should be detectable.

**Comment by mleko69** [comment]
I have the same issue, on my console error says:
>Icon theme "ubuntu-mono-dark" not found.
>Icon theme "Mint-X" not found.
>Icon theme "elementary" not found.

I'm also a Manjaro KDE user

**Comment by mleko69** [comment]
I've found a solution/workaround - it's related to the icon theme. Edit the index.theme in your icon pack folder and in the line "Inherits" remove names of icons you don't have installed.

**Comment by michaldybczak** [comment]
Not sure what you mean. What index.theme file? Where? In ~/.icons I see only folders for certain icon packs. I don't have elementary icons there, nor in ~/.themes folder.

**Comment by mleko69** [comment]
Yes, and inside the folder of the icon pack you're currently using is a file called **index.theme**. Open it with text editor and remove the names of icons you don't have installed, just like on the screenshot below:
![obraz](https://user-images.githubusercontent.com/22177132/29708356-a4231640-8988-11e7-8133-9a7e70b24aa7.png)

It would be easier if screenfetch could just ignore that message.

**Comment by darealshinji** [comment]
> It would be easier if screenfetch could just ignore that message.
Ignore the entire `Inherits` line?

**Comment by mleko69** [comment]
>Ignore the entire Inherits line?

Yes, I think. Inherits are the icons that are borrowed from other packs in case when one icon theme doesn't have such an icon.

**Comment by michaldybczak** [comment]
**Thanks @mleko69, I edited out elementary of inherits line. That is the solution.**

The question is: why this leftover exist? Something clearly failed to update the file after deletion. Probably with all the setting changes and rolling updates some small things can go south.

Also, screenfetch is just a cool showy thing and reading inherits is completely not necessary. For info tool, that might be a different thing but screenfetch is just desktop simple showdown.

**Comment by darealshinji** [comment]
I'm unsure which part of the theme detection in the script I should edit. Can someone with this problem figure it out and make a pull request?
