### ISSUE TITLE
Add support for windows 10 

### ISSUE THREAD

**Issue by atiwiex** [KittyKatt/screenFetch#498]
It would be nice to have windows 10 support and not just bash on windows 10

**Comment by darealshinji** [comment]
How exactly should that work? Windows is not POSIX compatible. You can use this script only if you have some kind of POSIX layer like "Bash on Windows" or Cygwin.
[screenfetch-c](https://github.com/woodruffw/screenfetch-c) can be compiled with MinGW and run straight from Windows command prompt, maybe that's what you're looking for?

**Comment by atiwiex** [comment]
I figured it out. If you clone the repo using git bash then in git bash do bash screenfetch-dev it works.

**Comment by darealshinji** [comment]
Can this be closed then?

**Comment by atiwiex** [comment]
Ill close it
