### ISSUE TITLE
Amazon Linux

### ISSUE THREAD

**Issue by lucamosca1** [KittyKatt/screenFetch#504]
Hi! I'm testing on amazon linux
OS seems detected correctly, but there are generic logo and I see
Packages: Unknown

Cheers
Luca

**Comment by darealshinji** [comment]
Is it this? -> https://aws.amazon.com/amazon-linux-ami/
Package manager is yum. Does it count the packages if you run it as `screenfetch -D 'Fedora'`? Does this distro even have an official logo? What's the output of `screenfetch -v`?

**Comment by lucamosca1** [comment]
Is it this? -> https://aws.amazon.com/amazon-linux-ami/
[l] yes
Does it count the packages if you run it as screenfetch -D 'Fedora'?
[l] yes
Does this distro even have an official logo?
[l] Nice question, I would say that logo is the AWS one https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/AmazonWebservices_Logo.svg/1280px-AmazonWebservices_Logo.svg.png But I'm not sure
What's the output of screenfetch -v?
[l]
:: Finding distro...found as 'amzn '
:: Finding hostname and user...found as 'user@ec2'
:: Finding kernel version...found as 'x86_64 Linux 4.9.32-15.41.amzn1.x86_64'
:: Finding current uptime...found as '3d 20h 43m'
:: Finding current package count...found as 'Unknown'
:: Finding current shell...found as 'bash 4.2.46'
:: Finding current resolution(s)...found as ''
:: Finding desktop environment...found as 'Not Present'
:: Finding window manager...found as 'Not Found'
:: Finding window manager theme...found as 'Not Found'
:: Finding GTK2 theme...found as 'Not Found'
:: Finding GTK3 theme...found as 'Not Found'
:: Finding icon theme...found as 'Not Found'
:: Finding user font...found as 'Not Found'
:: Finding current CPU...found as 'Intel Xeon E5-2676 v3 @ 2.4GHz'
:: Finding current GPU...found as 'Not Found'
:: Finding current RAM usage...found as '38MiB / 993MiB'
                             user@ec2
                             OS: amzn 
                             Kernel: x86_64 Linux 4.9.32-15.41.amzn1.x86_64
         #####               Uptime: 3d 20h 43m
        #######              Packages: Unknown
        ##O#O##              Shell: bash 4.2.46
        #######              CPU: Intel Xeon E5-2676 v3 @ 2.4GHz
      ###########            RAM: 38MiB / 993MiB
     #############          
    ###############         
    ################        
   #################        
 #####################      
 #####################      
   #################

**Comment by darealshinji** [comment]
Added Amazon Linux detection. I'll now try to create an ASCII logo from one of these orange AWS boxes.

**Comment by dylanaraps** [comment]
I've made one, feel free to use it.

```sh
            `-/oydNNdyo:.`
      `.:+shmMMMMMMMMMMMMMMmhs+:.`
    -+hNNMMMMMMMMMMMMMMMMMMMMMMNNho-
.``      -/+shmNNMMMMMMNNmhs+/-      ``.
dNmhs+:.       `.:/oo/:.`       .:+shmNd
dMMMMMMMNdhs+:..        ..:+shdNMMMMMMMd
dMMMMMMMMMMMMMMNds    odNMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
dMMMMMMMMMMMMMMMMh    yMMMMMMMMMMMMMMMMd
.:+ydNMMMMMMMMMMMh    yMMMMMMMMMMMNdy+:.
     `.:+shNMMMMMh    yMMMMMNhs+:``
            `-+shy    shs+:`

```

**Comment by darealshinji** [comment]
I've added a logo.
