### ISSUE TITLE
Add support for Source Mage

### ISSUE THREAD

**Issue by asdfjk1** [KittyKatt/screenFetch#505]
Source Mage is an indepdendent source based distro that works in a few ways similar to gentoo. It uses a package manager called sorcery written in bash and it gets the latest stable package straight from upstream rather than keeping its own cache of packages. It's pretty promising of a distro.
https://sourcemage.org

This is what I believe is what the logo is supposed to be since I've seen different versions of it online, do you think you should just use the raven as the logo since the whole one might look too big or too ugly.
![smgl_logo](https://user-images.githubusercontent.com/30349430/28470229-1a13d468-6e07-11e7-894d-7c8ab5a4c1dc.png)

**Comment by asdfjk1** [comment]
Awesome, now just needs to be added to screenfetch.

**Comment by dylanaraps** [comment]
For the package manager you can use `gaze installed | wc -l` to count the installed packages.

**Comment by karasuma-chitose** [comment]
I made it a bit smaller to fit the screenfetch properly
```
      -sdNMNds:    
.shmNMMMMMMNNNNh.               
 ` ':sNNNNNNNNNNm-              
     .NNNNNNmmmmmdo.            
    -mNmmmmmmmmmmddd:           
    +mmmmmmmddddddddh-          
    :mmdddddddddhhhhhy.         
    -ddddddhhhhhhhhyyyo         
    .hyhhhhhhhyyyyyyyys:        
     .`shyyyyyyyyyssssso        
       `/yyyysssssssoooo.   
         .osssssooooo+++/   
          `:+oooo+++++///.  
           `://++//////::-  
       ..-///  .//::::::--. 
      ```` ```  :::--------`
                `------....`
                 `.........`
                   `......` 
```
Bold black color for the raven and red for the labels fit the SMGL theme and look nice imo.
This is how it'd look like
![screenfetch](https://my.mixtape.moe/bjwnmh.png)

**Comment by asdfjk1** [comment]
Looks very nice, if everything is in proper order and you're done, could you please pull request that.

**Comment by vinpublic** [comment]
check out PR #506 . Thank you, @karasuma-chitose for ASCII logo.

**Comment by darealshinji** [comment]
Merged PR.

**Comment by vinpublic** [comment]
btw, now you can install screenfetch using test grimoire and this command:
cast screenfetch
