### ISSUE TITLE
Typo in the Source Mage GNU/Linux logo color declaration

### ISSUE THREAD

**Issue by karasuma-chitose** [KittyKatt/screenFetch#507]
It says `c1=$(getColor 'dark gray')` instead of `c1=$(getColor 'dark grey')`.

**Comment by darealshinji** [comment]
It's not a typo. "gray" is American English, "grey" is British English.

**Comment by darealshinji** [comment]
Should be fixed with https://github.com/KittyKatt/screenFetch/commit/ed1020c196995faa4ff6cfd3691f9d777e157c49
