### ISSUE TITLE
Fix Source Mage GNU/Linux formatting

### ISSUE THREAD

**Issue by ayuiz** [KittyKatt/screenFetch#513]
It looks pretty bad like this, with no space between the logo and the command line:
![screenfetch1](https://my.mixtape.moe/cnshjl.png)
it's much better with an empty line in between like this:
![screenfetch2](https://my.mixtape.moe/ghbyfs.png)
Also, it'd be nice if the text started at least one line after the start of the logo.

**Comment by darealshinji** [comment]
Does it now look better?

**Comment by ayuiz** [comment]
Now it has two <user@hostname>'s.
![](https://my.mixtape.moe/rntjhy.png)

**Comment by darealshinji** [comment]
I should have tested it. Now it doesn't produce the double line.

**Comment by ayuiz** [comment]
Looks good now.
