### ISSUE TITLE
Screenfetch suport for ALDOS.

### ISSUE THREAD

**Issue by darkshram** [KittyKatt/screenFetch#521]
Please, add support for [ALDOS](http://www.alcancelibre.org/staticpages/index.php/notas-lanzamiento-aldos-1-4). I have already done the patch.
[screenFetch-3.8.0-ALDOS.zip](https://github.com/KittyKatt/screenFetch/files/1345209/screenFetch-3.8.0-ALDOS.zip)

**Comment by darealshinji** [comment]
Can you make a pull request on Github please?
