### ISSUE TITLE
Getting "No such file or directory" and hang after CPU temp fix on macOS

### ISSUE THREAD

**Issue by zero298** [KittyKatt/screenFetch#527]
I'm getting the following error and a hang after cf73671d4d46552696e1052e6039244e2d7dc4a1

```
ls: /sys/class/hwmon/: No such file or directory
```

No further output and no exit after the error.

6481b7e9424b4123b46301a941809e837b69eb9e, immediately before #526 works fine though.

**Comment by Contik** [comment]
I'm seeing the same behavior on an OpenVZ virtual machine, in my case simply because in environments such as this one `/sys/class/hwmon` may not necessarily exist.

**Comment by zero298** [comment]
Yep, working correctly now.  Thanks!
