### ISSUE TITLE
ChromeOS removed 'wget'

### ISSUE THREAD

**Issue by DennisLfromGA** [KittyKatt/screenFetch#534]
I'm not sure about Chromium OS but just recently Chrome OS has removed the '`wget`' command so '`curl`' is used instead.

Perhaps the README.mkdn ln\#28 could be changed to something like:

1. Download the executable file and put it under the `/usr/local/bin/` directory: `sudo curl -# -o /usr/local/bin/screenfetch-dev https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev`

~DennisL

**Comment by darealshinji** [comment]
It's updated.

**Comment by DennisLfromGA** [comment]
Thanx, that was quick. 👍
