### ISSUE TITLE
/etc/os-release vs /usr/lib/os-release

### ISSUE THREAD

**Issue by oaken-source** [KittyKatt/screenFetch#536]
screenFetch seems to only check for the os-release file in /etc/os-release, but another possible location for the file would be /usr/lib/os-release, as stated here:
https://www.freedesktop.org/software/systemd/man/os-release.html

In fact, on parabola GNU/Linux, /etc/os-release used to be a symlink to /usr/lib/os-release, and apparently is missing from current releases, which causes the distro to be incorrectly identified as arch.

An easy way to fix this would be to check for both /etc/os-release and /usr/lib/os-release.

**Comment by darealshinji** [comment]
I've added some checks: https://github.com/KittyKatt/screenFetch/commit/e1a90cc33aeb140560d3261b4df3540aa1c97758

**Comment by oaken-source** [comment]
thank you, I can confirm that it works as expected now :)
