### ISSUE TITLE
Maybe a spelling mistake. 

### ISSUE THREAD

**Issue by whoisnian** [KittyKatt/screenFetch#538]
When I try `cat /proc/meminfo` in my Arch Linux and CentOS, I both get 'Shmem' but not 'ShMem'. 
In Memory Detection part of the 'screenfetch-dev', there is 'ShMem' in line 1519.

**Comment by darealshinji** [comment]
Yes, a mistake. I also realize that the size displayed is a multiple of 10, not 2, as the `i` in `MiB` implies. I'm also getting a slightly different value on the MATE desktop monitor for used memory. Not calculating out the `"Buffers"` value gives me the same value. I'll do some more testing to figure out which value is the correct one. It should probably be checked on non-Linux systems too whether the given value is a multiple of 2 or 10.
