### ISSUE TITLE
Add support for MagpieOS

### ISSUE THREAD

**Issue by Rizwan-Hasan** [KittyKatt/screenFetch#544]
It will be very helpfull for me if screenfetch add suports for MagpieOS.
http://magpieos.net

**Comment by KittyKatt** [comment]
@Rizwan-Hasan Would you mind posting a link to some kind of logo asset? Something I can make the ASCII out of. Thanks

**Comment by Rizwan-Hasan** [comment]
![magpie os-green transparent](https://user-images.githubusercontent.com/16849373/37552082-046fea7e-29d8-11e8-9e76-936fd69dc5de.png)

**Comment by Rizwan-Hasan** [comment]
​

**Comment by Rizwan-Hasan** [comment]
![screenshot from 2018-04-13 13-01-31](https://user-images.githubusercontent.com/16849373/38721180-ee41b040-3f1a-11e8-9a5a-8f256ff16294.png)
