### ISSUE TITLE
Add Support for PureOS

### ISSUE THREAD

**Issue by wellton** [KittyKatt/screenFetch#553]
Hello, 

the PureOS is the Puri.sm`s Operating System. Could you please add support for PureOS in Screenfetch?
thanks!!

the cat /etc/*release here:

![captura de tela de 2018-04-22 10-02-26](https://user-images.githubusercontent.com/2234645/39095286-4e63d598-4614-11e8-9714-a9b4294b95fd.png)

**Comment by wellton** [comment]
Hi.. any news?

**Comment by dylanaraps** [comment]
Got a logo?

**Comment by darealshinji** [comment]
Well, that's a simple logo. Shouldn't be hard to add this.

**Comment by wellton** [comment]
cool, I'll be waiting then.

**Comment by dylanaraps** [comment]
Here's an ascii logo I made:

```
dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd
dNm//////////////////////////////////mNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNd                                  dNd
dNm//////////////////////////////////mNd
dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd
```

**Comment by wellton** [comment]
show...  any date to enter the new release of screenfetch?

**Comment by darealshinji** [comment]
What package manager does it use? How do you list the installed packages?

**Comment by darealshinji** [comment]
I've added support for PureOS. Can you check it?

**Comment by wellton** [comment]
Hello, yes, pureOS is based on Debian. Apt is used.

**Comment by wellton** [comment]
wow... very beautiful...  =) thanks. The screenFetch project is strong. =)

![captura de tela em 2018-06-02 08-42-45](https://user-images.githubusercontent.com/2234645/40874063-f4c46438-6640-11e8-942a-bcba3fb98e2f.png)

**Comment by lamby** [comment]
FYI this is being tracked within PureOS itself here: https://tracker.pureos.net/T464
