### ISSUE TITLE
Getting error with readlink on macOS

### ISSUE THREAD

**Issue by erankitarora** [KittyKatt/screenFetch#562]
In this part of code where readlink is called, there is an invalid option -f which is given as an output when screenfetch is run:

elif readlink -f "$SHELL" 2>&1 | grep -q -i 'busybox'; then --> Here, -f can be avoided on macOS.

command run: **/usr/local/bin/screenfetch**
**readlink: illegal option -- f
usage: readlink [-n] [file ...]**
                               
                 -/+:.          
                :++++.          OS: 64bit Mac OS X 10.13.1 17B1003
               /+++/.           Kernel: x86_64 Darwin 17.2.0
       .:-::- .+/:-``.::

**Comment by darealshinji** [comment]
Are you using the latest version from Github?

**Comment by erankitarora** [comment]
screenfetch --version
screenFetch - Version 3.8.0

This is the version.

**Comment by erankitarora** [comment]
![image](https://user-images.githubusercontent.com/8296708/40888302-eea60b46-6772-11e8-9e17-3232ecccd8e1.png)

As it can be seen in the screenshot, the latest master branch of screenfetch has the -f option with readlink and I saw readlink does not have any upgrades for macOS.

**Comment by darealshinji** [comment]
Use the latest version from this repository: `brew reinstall screenfetch --HEAD`

I think brew should either install a newer snapshot or patch the release version. Maybe you can file a bug report there: https://github.com/Homebrew/homebrew-core/issues

See also: https://github.com/KittyKatt/screenFetch/issues/552 https://github.com/KittyKatt/screenFetch/issues/456

**Comment by darealshinji** [comment]
Latest version still has it? Hmm, can you make a pull request with a fixed version?

**Comment by erankitarora** [comment]
It looks fixed now.
