### ISSUE TITLE
awk: fatal: cannot open file `proc/fb' for reading on Ubuntu 18.04 for Windows 10

### ISSUE THREAD

**Issue by DavidBerdik** [KittyKatt/screenFetch#563]
This issue is similar to the one reported [here](https://github.com/KittyKatt/screenFetch/issues/449). After updating to Ubuntu 18.04 for Windows 10, this error appears. The only difference is that the `/usr/bin/screenfetch: line 1341: [: =: unary operator expected` is not present.

**Comment by jens1o** [comment]
Also on Kali Linux for WSL

**Comment by zlhysong-lkw** [comment]
Can confirm this happens on Kali Linux for WSL.
![image](https://user-images.githubusercontent.com/40303544/41863682-8cf10252-7875-11e8-9b80-80998dd454f4.png)

**Comment by Colopatiron** [comment]
Same here.

![2018-07-13 7](https://user-images.githubusercontent.com/1519903/42674031-bfa2889a-86a0-11e8-8798-e06a81cd2bec.png)

**Comment by darealshinji** [comment]
This should be fixed on the latest version from this repository:

![screen-2018-07-16_20-23-07](https://user-images.githubusercontent.com/5700937/42776154-804ebe14-8936-11e8-9baf-d2231044c8d9.png)

The screenFetch versions you're using seem to be outdated.

**Comment by phifa** [comment]
Same error over here. Just installed via `sudo apt install screenfetch`

![grafik](https://user-images.githubusercontent.com/3061129/43774908-0dec3240-9a4b-11e8-8476-d653084c7fec.png)

**Comment by darealshinji** [comment]
@phifa Again folks, please download the latest script revision from **Github**. The version installed with apt is outdated.

**Comment by phifa** [comment]
@darealshinji ok sounds great, how would I go about installing it? I download the dev master from Github?

**Comment by abdalrohman** [comment]
Downlode the latest version from here **`wget -O screenfetch-dev https://git.io/vaHfR`**
Then **`sudo rm /usr/bin/screenfetch`**
After that go to the folder where downlode **_screenfetch-dev_** and rename the **_screenfetch-dev_** to **_screenfetch_**
**`chmod +x screenfetch`**
Now move the screenfetch to the **`sudo mv screenfetch /usr/bin`**

**Comment by Akito13** [comment]
> 
> 
> Downlode the latest version from here **`wget -O screenfetch-dev https://git.io/vaHfR`**
> Then **`sudo rm /usr/bin/screenfetch`**
> After that go to the folder where downlode **_screenfetch-dev_** and rename the **_screenfetch-dev_** to **_screenfetch_**
> **`chmod +x screenfetch`**
> Now move the screenfetch to the **`sudo mv screenfetch /usr/bin`**

This solved it for me on Ubuntu 18.04 on Windows, thank you.

**Comment by DavidBerdik** [comment]
@abdalrohman Thanks! That seems to have solved it!

**Comment by artmak** [comment]
> 
> 
> Downlode the latest version from here **`wget -O screenfetch-dev https://git.io/vaHfR`**
> Then **`sudo rm /usr/bin/screenfetch`**
> After that go to the folder where downlode **_screenfetch-dev_** and rename the **_screenfetch-dev_** to **_screenfetch_**
> **`chmod +x screenfetch`**
> Now move the screenfetch to the **`sudo mv screenfetch /usr/bin`**

This fix it for me on Ubuntu 18.04 on Windows, thank you.

**Comment by digitalfiz** [comment]
Why not update the apt package?

**Comment by aljagne** [comment]
thanks

**Comment by memark** [comment]
> @phifa Again folks, please download the latest script revision from **Github**. The version installed with apt is outdated.

When will the apt package be updated?

**Comment by jhelfman** [comment]
> > @phifa Again folks, please download the latest script revision from **Github**. The version installed with apt is outdated.
> 
> @abdalrohman When will the apt package be updated?

File a bug report with vendor to update the package.
https://packages.debian.org/sid/utils/screenfetch

**Comment by KittyKatt** [comment]
Release pushed, packages can be updated.

**Comment by revpixel** [comment]
> > Downlode the latest version from here **`wget -O screenfetch-dev https://git.io/vaHfR`**
> > Then **`sudo rm /usr/bin/screenfetch`**
> > After that go to the folder where downlode **_screenfetch-dev_** and rename the **_screenfetch-dev_** to **_screenfetch_**
> > **`chmod +x screenfetch`**
> > Now move the screenfetch to the **`sudo mv screenfetch /usr/bin`**
> 
> This fix it for me on Ubuntu 18.04 on Windows, thank you.

Had to do exactly this to pull  3.9.1 on Suse Leap for WSL 2.

**Comment by vi11ain** [comment]
apt is still outdated...

**Comment by luisAzcuaga** [comment]
> Downlode the latest version from here **`wget -O screenfetch-dev https://git.io/vaHfR`**
> Then **`sudo rm /usr/bin/screenfetch`**
> After that go to the folder where downlode **_screenfetch-dev_** and rename the **_screenfetch-dev_** to **_screenfetch_**
> **`chmod +x screenfetch`**
> Now move the screenfetch to the **`sudo mv screenfetch /usr/bin`**

This helped me on Debian 10 (WSL2) 🥳
