### ISSUE TITLE
Opensuse Leap 15 (or Opensuse Tumbleweed) is not properly recognized as a openSUSE distro

### ISSUE THREAD

**Issue by halars** [KittyKatt/screenFetch#566]
Running screenfetch, using opensuse leap 15, I get the generic tux image, and the OS is identified as:
"opensuse-leap"

(Tumbleweed is identified as "opensuse-tumbleweed", again with the generic tux image)

**Comment by khalil2535** [comment]
I got this
![image](https://user-images.githubusercontent.com/26520106/44309051-0906e180-a3c9-11e8-9cc4-50dc74bbe953.png)

**Comment by halars** [comment]
For me it is still the same. But strangely your OS is "openSUSE 15.0", while mine is "opensuse-leap".

**Comment by khalil2535** [comment]
I am new for everything , am i using another fork ?
![image](https://user-images.githubusercontent.com/26520106/44309123-82eb9a80-a3ca-11e8-8adf-e0f838bbe837.png)

**Comment by Fubuchi** [comment]
@halars 

Open the file _screenfetch-dev_ and your favourite editor. Go to line 897 and add this : 

    verboseOut "Distro name : ${distro}"

Run screenfetch with verobse `-v` flag to see what is your distro name (in my case it is `Opensuse-leap`). Remove the verboseOut you just added (or not if you want 😄 ).

Now, add this line to the "Hotfixes" segment at line 898 and everything will be good.

    [[ "${distro}" == "the-name-you-got-from-above-step" ]] && distro="openSUSE"

I can get the right suse logo on my WSL running openSUSE leap 15 after add the above hotfix:

![image](https://user-images.githubusercontent.com/42483897/50046856-0305e080-00dd-11e9-83b7-e1bb0464bbc8.png)

**Comment by pa-jberanek** [comment]
For me, with openSUSE 15.0 on WSL, installing 'lsb-release' fixed the distro determination without the hot fix above, and lead to:

OS: openSUSE 15.0(on the Windows Subsystem for Linux)

**Comment by jberanek** [comment]
Created a PR with a hotfix, for when you don't have lsb-release installed:
https://github.com/KittyKatt/screenFetch/pull/609
