### ISSUE TITLE
cannot open file /proc/fb on Ubuntu 18 on Windows 10

### ISSUE THREAD

**Issue by clragon** [KittyKatt/screenFetch#584]
Hello there,

```awk: fatal: cannot open file `/proc/fb' for reading (No such file or directory)```

![screenshot_1](https://user-images.githubusercontent.com/11785085/43371442-91990420-9392-11e8-8dbe-63c69e7830c6.png)

This good ol' issue is back at it again with the newest Bash on Ubuntu (18, bionic) on Windows 10

Can this be fixed?

thanks in advance.

**Comment by darealshinji** [comment]
Have you tried the latest script version from Github?
https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev

**Comment by jdhao** [comment]
Using the latest screenfetch-dev resolves this issue.
