### ISSUE TITLE
Support for CoreOS

### ISSUE THREAD

**Issue by wavengine** [KittyKatt/screenFetch#586]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] new distro request
```

**Bug report**
```
=> search Github for a similar issue or PR before submitting
=> download the latest revision from Github and check if the bug is still present
   -> https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev
=> Show us the output of: screenfetch -v
```

**New distro request**
```
Distro name: CoreOS
Homepage: https://coreos.com/
Distro logo: https://pbs.twimg.com/profile_images/378800000217543291/92f941aa760503ef8552a9fbc77ef9b6_400x400.png
Package manager: dnf

Show us the output of
 => lsb_release -sirc
 => cat /etc/os-release
 => ls -1 /etc/*-release
```

**Comment by darealshinji** [comment]
@cdancy posted that the CoreOS project was "dead": https://github.com/KittyKatt/screenFetch/issues/249#issuecomment-372288983
Is CoreOS still available as a distro?

Also you didn't show the output of the following commands:
```
 => lsb_release -sirc
 => cat /etc/os-release
 => ls -1 /etc/*-release
```
That's needed for the distro detection. However in https://github.com/KittyKatt/screenFetch/issues/249 that user posted the content of /etc/os-release and /etc/lsb-release: https://github.com/KittyKatt/screenFetch/issues/249#issuecomment-114193206

**Comment by wavengine** [comment]
Sorry, I just know it.

**Comment by haximilian** [comment]
@Vndroid Good News! Container Linux (that's the official name for the operating system you call "CoreOS") is not actually dead. For more information, please refer to my comment under #249. I recommend that we continue discussion of this feature request under #249 for now, so as to avoid creating a duplicate issue.
