### ISSUE TITLE
Error detecting Window Manager on OSX

### ISSUE THREAD

**Issue by ifonefox** [KittyKatt/screenFetch#59]
Instead of getting 'Quartz Compositor', it now gets '_net_wm_name: not found'. Also, whenever I run screenfetch now, XQuartz (X11) opens as well.

**Comment by KittyKatt** [comment]
Closed from no response for 6 years.

**Comment by ifonefox** [comment]
I'm sorry for not responding. I can confirm that it shows the correct window manager when using the latest commit (3248e59) on macOS 10.14.6.
