### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by coughll** [KittyKatt/screenFetch#597]
I'm back! 

I'd appreciate it if you tagged a new release (either 3.8.1 or 3.9 or whatever you want) so homebrew and other git based package managers to download the later version. I ran into this problem after I reinstalled screenfetch after my bugfix last week was merged, and found that homebrew downloads the archived releases and not the up-to-date .git files. If/when you tag a new release, I'll submit a pr on the homebrew github to link to the new release. 

The repo has at least 2 macos bugs fixed that aren't in the archived release, and it works fine on the 2 macos versions I've tried(10.12 and 10.13).

**Comment by darealshinji** [comment]
@KittyKatt ? Should a new release be tagged? Anything important that needs to be done before?

**Comment by KittyKatt** [comment]
@darealshinji I think tagging a new major release sounds like a good idea. Nothing to really do beforehand besides edit the version string in screenfetch-dev and any other relevant files.

**Comment by darealshinji** [comment]
Sure, go ahead and tag a new release.

**Comment by TsarFox** [comment]
Any updates on this? GuixSD is interested in a version we can track, but 3.8.0 doesn't detect us.

**Comment by darealshinji** [comment]
@KittyKatt ?

**Comment by Alessandro-Barbieri** [comment]
I need this on gentoo, important changes made since last version

**Comment by otherguy** [comment]
There are a lot of changes since the last release: https://github.com/KittyKatt/screenFetch/compare/v3.8.0...master

I would also appreciate a new version and [looking at the release history](https://github.com/KittyKatt/screenFetch/releases), it does not seem like there is a super strict versioning scheme.

I think just tagging it as `3.9.0` would be fine.

If you want me to, I can take care of preparing a release.

**Comment by KittyKatt** [comment]
v3.9.0 has been tagged and released.

**Comment by jhelfman** [comment]
> v3.9.0 has been tagged and released.

I was planning on putting in a pull request for this, but the scriptversion still states 3.8.0, as well as the man page.

**Comment by KittyKatt** [comment]
@jhelfman  Ah, thanks for catching that! I'll update it today.
