### ISSUE TITLE
GPU detection not working

### ISSUE THREAD

**Issue by Bankara** [KittyKatt/screenFetch#61]
My GPU is being detected as "not found".
A buddy with the same chip set is not having this issue, and I can't figure out what's failing.
lspci and glxinfo are installed and working:
http://pastebin.com/ubA5Np15

**Comment by panaino** [comment]
Since /usr/sbin is not in your $PATH

**Comment by KittyKatt** [comment]
Hm, interesting. Could you try latest just to be sure. A pull request regarding GPU detection was just merged.

**Comment by panaino** [comment]
I think my commit won't fix this issue, because he can execute lspci/glxinfo in home directory(~).

**Comment by KittyKatt** [comment]
Closing this due to being 4 years old with no response.
