### ISSUE TITLE
line 2231: warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by briancrink** [KittyKatt/screenFetch#613]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] new distro request
```

**Bug report**
```
=> search Github for a similar issue or PR before submitting
=> download the latest revision from Github and check if the bug is still present
   -> https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev
=> Show us the output of: screenfetch -v
```
:: Finding distro...found as 'Mac OS X '
:: Finding hostname and user...found as 'briancrink@MacBook-Pro'
:: Finding kernel version...found as 'x86_64 Darwin 18.6.0'
:: Finding current uptime...found as '2d 1h 2m'
:: Finding current package count...found as '208'
:: Finding current shell...found as 'bash 5.0.7'
:: Finding current resolution(s)...found as '2560x1600'
:: Finding desktop environment...found as 'Aqua'
:: Finding window manager...found as 'Quartz Compositor'
:: Finding window manager theme...found as 'Blue'
:: Finding GTK2 theme...found as 'Not Applicable'
:: Finding GTK3 theme...found as 'Not Applicable'
:: Finding icon theme...found as 'Not Applicable'
:: Finding user font...found as 'OperatorMono-Medium 13'
:: Finding current CPU...found as 'Intel Core i7-5557U @ 3.10GHz'
:: Finding current GPU...found as 'Intel Iris Graphics 6100 '
:: Finding current RAM usage...found as '6464MiB / 16384MiB'

Show us the output of
 => lsb_release -sirc
`bash: lsb_release: command not found`
 => cat /etc/os-release
`cat: /etc/os-release: No such file or directory`
 => ls -1 /etc/*-release
`s: cannot access '/etc/*-release': No such file or directory`
```
**Note: the warning exists in Mac's native Terminal but does not exist in iTerm2.**

**Comment by darealshinji** [comment]
Line 2231 doesn't look any special. Have you tried the latest snapshot from Github?

**Comment by briancrink** [comment]
`screenfetch --version` -> 3.8.0 I'm not sure where the bug came from but at some point after reinstalling coreutils from homebrew, resetting $PATH, and creating a new Terminal Profile, the `line 2231 command substitution warning` is gone. 

My bash_profile:
```
export PATH=""
export PATH="/sbin:$PATH"
export PATH="/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="$HOME/bin:$PATH";
export PATH="/usr/local/sbin:$PATH";
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```
