### ISSUE TITLE
Wrong system information in macOS

### ISSUE THREAD

**Issue by ivan-avalos** [KittyKatt/screenFetch#615]
```
[x] bug report
[ ] new distro request
```
### Bug report

**How it should be:**
```
macOS = platform.
Darwin = operating system.
XNU = kernel.
```

**Current situation:**
```
macOS = operating system.
Darwin = kernel.
XNU = ???
```

### Output
```
                 -/+:.          xxxx@xxxx
                :++++.          OS: 64bit Mac OS X 10.14.3 18D109
               /+++/.           Kernel: x86_64 Darwin 18.2.0
       .:-::- .+/:-``.::-       Uptime: 3d 6h 11m
    .:/++++++/::::/++++++/:`    Packages: 412
  .:///////////////////////:`   Shell: bash 3.2.57
  ////////////////////////`     Resolution: 1440x900
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Font: SFMono-Regular
  osssssssssssssssssssssssso/`  CPU: Intel Core i5-5350U @ 1.80GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: Intel HD Graphics 6000 
   `ossssssssssssssssssssss/    RAM: 3820MiB / 8192MiB
     :ooooooooooooooooooo+.    
      `:+oo+/:-..-:/+o+/-      

```

**Comment by darealshinji** [comment]
I guess `Mac OS X` should be changed to `macOS` anyway. XNU as kernel name makes sense. But there is no "platform" line in screenFetches output.
What exactly does `uname -o` and `uname -s` print?

**Comment by ivan-avalos** [comment]
Yeah, there's no platform line, but you can't put macOS as the operating system because the actual operating system is called Darwin. It doesn't make sense to consider macOS as an operating system, even though Apple wants people to call it that way.

```
Darwin = operating system.
XNU = kernel.
```

**Comment by darealshinji** [comment]
For me it says OS is Ubuntu which is not the actual OS name either, `GNU/Linux` would be correct. On the other side, saying that my OS name is Ubuntu isn't completely wrong. I don't know if I really want to change that. You could of course separate it into OS and distro. In my case I would get `Distro: Ubuntu`, `OS: GNU/Linux` and `Kernel: Linux`, for you it would be `Distro: macOS`, `OS: Darwin` and `Kernel: XNU`. For most other OSes you would ommit the distro entry.

**Comment by ivan-avalos** [comment]
Well, that would be a great idea, separating both different things.

**Comment by ivan-avalos** [comment]
Now I think this is irrelevant.
