### ISSUE TITLE
My Tux's Arm is Broken!

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [KittyKatt/screenFetch#618]
The command I use in bashrc is "screenfetch -A 'Penguin'set +o history"
The arm on our right (where the mouse is in the screenshot) isn't two hashtags big like the one on our left. Any chance of a fix?

![Screenshot_2019-05-19_02-12-06](https://user-images.githubusercontent.com/7698035/57976583-92d8ef00-79db-11e9-864c-05aa37d48a78.png)

**Comment by darealshinji** [comment]
The right side is supposed to be thicker because of Tux's pose:

![220px-Tux](https://user-images.githubusercontent.com/5700937/57976902-ebb08380-79eb-11e9-838e-307ddbee9209.png)

I'm closing this issue, okay?

**Comment by KUPOinyourWINDOW** [comment]
Oh my bad! I didn't realise, sorry for the hassle
