### ISSUE TITLE
3.8.1 Release

### ISSUE THREAD

**Issue by alex-mohemian** [KittyKatt/screenFetch#641]
Any info when 3.8.1 will be released?

There are quite a lot of fixes already in master since the last release: https://github.com/KittyKatt/screenFetch/compare/v3.8.0...master

**Comment by darealshinji** [comment]
I don't know the versioning scheme behind this but I think the next version won't be 3.8.1 but something higher. As long as I don't know what version to tag a new release I won't do that. Unfortunately I @KittyKatt didn't respond for a while. See also https://github.com/KittyKatt/screenFetch/issues/597

**Comment by alex-mohemian** [comment]
I did not want to be presumptuous but you are right of course that the amount of changes warrant a 3.9.0 release at least ;)

Closing as duplicate of https://github.com/KittyKatt/screenFetch/issues/597
