### ISSUE TITLE
Don't see the point of this when neofetch exists

### ISSUE THREAD

**Issue by LothaireCliquennois** [KittyKatt/screenFetch#652]
Well, everything's in the title honestly

**Comment by KittyKatt** [comment]
Then don't use it.

Quite frankly, screenfetch came first. I do agree that neofetch has many things over screenfetch in terms of stability and overall writing but this is my project and if you really don't see a use for it, you're very much free to ignore its existence and never use it.

Closing this issue as WONTFIX and totally unnecessary.
