### ISSUE TITLE
Wont run on PowerShell Core as Get-WmiObject has been depreciated

### ISSUE THREAD

**Issue by ArnavD74** [KittyKatt/screenFetch#672]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] new distro request
```

**Bug report**
```
=> search Github for a similar issue or PR before submitting
=> download the latest revision from Github and check if the bug is still present
   -> https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev
=> Show us the output of: screenfetch -v
```

PS version: v7.1.0-preview.2, found on [https://github.com/PowerShell/PowerShell/releases](https://github.com/PowerShell/PowerShell/releases)
output: [https://imgur.com/a/cwAhd85](https://imgur.com/a/cwAhd85)
source: [https://github.com/PowerShell/PowerShell/issues/4766](https://github.com/PowerShell/PowerShell/issues/4766)

**Comment by darealshinji** [comment]
I think this is the project you're looking for, because this script here doesn't run in PowerShell or cmd.exe:
https://github.com/JulianChow94/Windows-screenFetch

**Comment by ArnavD74** [comment]
> 
> 
> I think this is the project you're looking for, because this script here doesn't run in PowerShell or cmd.exe:
> https://github.com/JulianChow94/Windows-screenFetch


yep, got confused my bad
