### ISSUE TITLE
Run screenfetch command automatically at terminal login

### ISSUE THREAD

**Issue by nguyenh13** [KittyKatt/screenFetch#691]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] new distro request
[x] question
```

**Question**
```
I wonder if there is a way that everytime I open teminal, the screenfetch command will be ran automatically?
```

**Comment by skielred** [comment]
There are various ways to achieve this. Simplest way is to add `screenfetch` to your local shell configuration file, ie `~/.bashrc` or `~/.zshrc` depending on what shell you use.

**Comment by darealshinji** [comment]
Just like @skielred said, actually a pretty simple task.
