### ISSUE TITLE
Mac OS Big Sur trouble

### ISSUE THREAD

**Issue by Wratheus** [KittyKatt/screenFetch#694]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] new distro request
```
![Снимок экрана 2020-11-27 в 18 30 38](https://user-images.githubusercontent.com/71131015/100464894-75f89e00-30df-11eb-9cb3-0854efd842f4.png)
Getting bunch of errs, using last Big Sur ver, screenfetch ver is 3.9.1
Also, when i'm running screenfetch command from my bashprofile (zsh links to bash) i'm getting err 
```bash
'Last login: Fri Nov 27 18:24:46 on ttys000
/Users/admin/.bash_profile:1: command not found: screenfetch'

```
I guess all of this errs are connected, he also can't detect the OS

**Comment by valjv** [comment]
Hey, solution here https://github.com/KittyKatt/screenFetch/issues/692#issuecomment-726631900
