### ISSUE TITLE
"Anonymous" Option

### ISSUE THREAD

**Issue by StefanLobbenmeier** [KittyKatt/screenFetch#695]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] new distro request
[ x] feature request
```

When posting the output of screenfetch somewhere I want to avoid sharing my name. Is there an option to not provide the username and pc name in the output?

If not, it would be nice if this was added. Might be extended to remove other attributes (ids, ip address (#693)) as well in case they are added.

**Comment by KittyKatt** [comment]
This is a great idea and something that's been kind of on my TODO list for a while. I've got an upcoming project, `fetch`, that you'll be able to do this with quite easily. I'll see if we can get something like this into screenfetch as well.

**Comment by KittyKatt** [comment]
Right now, with screenfetch's current supported output, you could execute screenfetch this way:

`screenfetch -d '-host'`

And it should remove the user@host line. Let me know if that works for you.

**Comment by StefanLobbenmeier** [comment]
Thanks, that works for me. I am not on my PC right now but looks good on my phone:


![2B5A6F8F-24D8-4C9B-A974-2B7EE4295873](https://user-images.githubusercontent.com/36509607/111847033-c8580780-88e6-11eb-89eb-084942833955.png)

![5D9264E4-400F-46DB-B1B6-8C9AB2B5F3AB](https://user-images.githubusercontent.com/36509607/111847038-ca21cb00-88e6-11eb-838d-f9a6e0e68d73.png)
