### ISSUE TITLE
Bad substitution line 2038: ${DESKTOP_SESSION}

### ISSUE THREAD

**Issue by Hunteerq** [KittyKatt/screenFetch#711]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] new distro request
```

**Bug report**
```
MacOS 11.2.1

/usr/local/bin/screenfetch: line 2038: ${DESKTOP_SESSION,,}: bad substitution
```
<img width="603" alt="Screenshot 2021-03-18 at 23 43 13" src="https://user-images.githubusercontent.com/15961002/111707268-08b27980-8844-11eb-8849-3b1db0dfca57.png">

**Comment by KittyKatt** [comment]
Thanks for reporting. I'll see if I have an environment around to test this.

**Comment by Hunteerq** [comment]
Sure, 


```
hunteerq@MacBook-Pro-Artur ~ % bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
hunteerq@MacBook-Pro-Artur ~ % printf "%s" "{$BASH_VERSION}"
{}%
hunteerq@MacBook-Pro-Artur ~ % bash -c "printf %s \"\$BASH_VERSION\""
3.2.57(1)-release%
hunteerq@MacBook-Pro-Artur ~ % zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
```

**Comment by KittyKatt** [comment]
The problem here is you have a BASH version below 4.0 installed. That's when ${var,,} was implemented. I can go through there and add a check for 4.0+ and if not, just use `tr` to get the same effect. Gimme a few and I'll try to have a fix out.

**Comment by KittyKatt** [comment]
@Hunteerq Can you pull from master and try the latest fix?

**Comment by Hunteerq** [comment]
It works, thank you :) 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/15961002/111797342-5de49e80-88c9-11eb-951d-23f401ae6a13.png">

**Comment by KittyKatt** [comment]
Not a problem at all. Happy it was such an easy fix. Closing!
