### ISSUE TITLE
m1 macbook support

### ISSUE THREAD

**Issue by japanese-goblinn** [KittyKatt/screenFetch#716]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] new distro request
```

**Bug report**
<img width="907" alt="Screenshot 2021-04-17 at 16 50 12" src="https://user-images.githubusercontent.com/33631005/115115398-fb042700-9f9c-11eb-8fef-3bacd4ed96d4.png">

**Comment by japanese-goblinn** [comment]
As far as i can tell problem is that for some reason script trying to read from `/proc` which is not available on `macOS`

**Comment by Raghav-Dixit** [comment]
I have the same problem, but I am on an Intel Mac (macOS v11.2.3).

**Comment by japanese-goblinn** [comment]
> I have the same problem, but I am on an Intel Mac (macOS v11.2.3).

well, that's pretty weird

**Comment by ironzombi** [comment]
fyi if you installed from homebrew, line 1051 in ```/usr/local/Cellar/screenfetch/3.9.1/bin/screenfetch``` (I installed from brew on 24th may 2021 intel mac v11.3.1)
```1051                     if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -i 'Mac OS X' >/dev/null; then```
change to
```1051                     if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -i 'macOS' >/dev/null; then```

**Comment by pbaudoux** [comment]
Thanks @ironzombi!

If the reported disk usage is wrong, you can change line 1717 to give `df` another mount point (default is `/`).

In my case I had to change it to:
`1717 totaldisk=$(df -H /System/Volumes/Data 2>/dev/null | tail -1)`

If support for M1 MacBook is added to screenfetch, is this something we can improve/modify ?
My educated guess is that this is related to APFS, so I think it affect all Macs with Sierra (10.12.4) or later.

**Comment by bonbisu** [comment]
> As far as i can tell problem is that for some reason script trying to read from `/proc` which is not available on `macOS`

@japanese-goblinn You can use `neofetch` as an alternative as long as it doesn't support m1 yet. Can be installed with `brew`.
https://github.com/dylanaraps/neofetch

**Comment by japanese-goblinn** [comment]
> fyi if you installed from homebrew, line 1051 in `/usr/local/Cellar/screenfetch/3.9.1/bin/screenfetch` (I installed from brew on 24th may 2021 intel mac v11.3.1)
> `1051 if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -i 'Mac OS X' >/dev/null; then`
> change to
> `1051 if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -i 'macOS' >/dev/null; then`

thanks
