### ISSUE TITLE
Bad name: Project does not do what name implies. It implies that it, itself, takes the screenshot.

### ISSUE THREAD

**Issue by mystica555** [KittyKatt/screenFetch#764]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] new distro request
```

**Bug report**
Your project is named wrong. It does nothing to fetch the screen to a file. 
I expected this to be a screenshot utility like xwd, import, scrot, etc.

**Comment by bsdjgh** [comment]
Screenshot:

https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L417

**Comment by KittyKatt** [comment]
I can understand your confusion, but the project will not be getting renamed. Closing as wontfix.
