### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by unixb0y** [KittyKatt/screenFetch#771]
I noticed some (many?) of the bugs being talked about in issues are fixed in the (latest, sometimes older version of the) main branch.
When users install screenfetch through package managers like Homebrew, they get by default v3.9.1 which is now 4 years old.
One example: https://github.com/KittyKatt/screenFetch/issues/685

Creating a new release from latest main (or whatever stable state after the last release) would be highly appreciated.

<img width="504" alt="Latest stable Homebrew version v3.9.1" src="https://github.com/KittyKatt/screenFetch/assets/6874233/828b11d5-781b-4513-a43e-4ffda0037c94">

**Comment by kalbasit** [comment]
@KittyKatt please do release a new version. I had many issues running it on my macOS and spent some time until I found the recommendation to install the HEAD version with Brew to fix all issues. Please 🙏🏽

**Comment by mohemiv** [comment]
https://github.com/KittyKatt/screenFetch/issues/788

This bug exists in 3.9.1, the only way to properly fix it is to make a release.

**Comment by KittyKatt** [comment]
I can try to get on this soon. Very sorry for the delay, life/work has been a hectic whirlwind and I've let a lot of my personal projects fall to the wayside. No promises on timeline, but this is on my radar.

**Comment by OpenSauce04** [comment]
Bump

**Comment by KittyKatt** [comment]
@OpenSauce04 @mohemiv @kalbasit @unixb0y A new release has been created. Sorry it took me so long.

**Comment by unixb0y** [comment]
@KittyKatt Thanks a lot!
