### ISSUE TITLE
ChromeOS

### ISSUE THREAD

**Issue by DennisLfromGA** [KittyKatt/screenFetch#91]
Just wondering if there's anyone else interested (besides me) in ChromeOS support for Chromebooks & Chromeboxes. Like a mono &/or color Chrome logo and support for Aura and Views? 
Reference: http://www.chromium.org/developers/design-documents/aura-desktop-window-manager

**Comment by darealshinji** [comment]
ChromeOS was added a while ago.

**Comment by idvoretskyi** [comment]
https://github.com/KittyKatt/screenFetch/pull/390
