### ISSUE TITLE
Red Hat Enterprise Linux 7 Beta

### ISSUE THREAD

**Issue by Broker824** [KittyKatt/screenFetch#99]
ScreenFetch run to new Red Hat Enterprise Linux 7 Beta

![screenshot 2013 12 15](https://f.cloud.github.com/assets/2772128/1750329/492bde2c-6586-11e3-91bd-2bfb58666d05.png)

Is that bug?

**Comment by KittyKatt** [comment]
Closing because this has been out of beta FOREVER and the issue probably no longer exists.
